/**
 * Neighborhood data table — 20 Queens neighborhoods that have towingservice* domains.
 *
 * RULES:
 * - Every fact here must be verifiable on a public Queens map / NYC subway map.
 * - No invented activity counts, no "we've responded 50 times to X intersection."
 * - subAreas are real sub-neighborhood names — open Wikipedia for any neighborhood and check.
 * - corridors are real commercial / arterial streets — must exist on a Queens street map.
 * - transit lists actual subway lines / stations / LIRR / bus that serve the area.
 * - geoAnchor: real geographic features (rivers, parks, bridges, highways).
 * - restrictedNearby: real NYC highways/parkways/bridges where NYPD-rotation contractors
 *   have exclusive access — we cannot service these. Only listed if actually adjacent.
 * - pattern: a structural reason calls cluster here. Service-agnostic.
 *   Must be defensible if Endri were asked "why did you write that?"
 * - responseMin: estimated arrival time in minutes from inside Queens. Geographic estimate
 *   (distance from staging areas + road network), not a measured SLA.
 */

module.exports = [
  {
    slug: 'astoria',
    name: 'Astoria',
    aliases: [],
    subAreas: ['Old Astoria', 'Steinway', 'Ditmars-Steinway', 'Halletts Point', 'Astoria Cove', 'Astoria Heights'],
    corridors: ['30th Avenue', 'Steinway Street', 'Ditmars Boulevard', 'Astoria Boulevard', 'Broadway'],
    transit: 'N/W trains along 31st Street (Astoria Blvd, 30th Ave, Broadway, 36th Ave, 39th Ave); M60-SBS to LaGuardia',
    parkingStyle: 'street-dense',
    housingType: 'small apartment buildings (4-6 stories), brownstones, row houses; high-rises at Halletts Point and Astoria Cove',
    geoAnchor: 'East River waterfront, Astoria Park, Hell Gate Bridge, RFK (Triborough) Bridge approach, BQE',
    responseMin: 20,
    lat: 40.7644,
    lng: -73.9235,
    restrictedNearby: ['BQE', 'RFK Bridge', 'Grand Central Parkway near LaGuardia', 'Astoria Boulevard elevated sections'],
    pattern: 'N/W subway-commuter weekday battery-drain pattern (cars sit Mon-Fri); East River cold-air pocket near Astoria Park drops overnight temps below borough average; 30th Avenue dinner crowd late-night calls',
    vanFitNote: 'narrow side streets between 21st St and Steinway with frequent double-parked cars — we dispatch the smaller service van, not a full flatbed',
  },

  {
    slug: 'long-island-city',
    name: 'Long Island City',
    aliases: ['LIC'],
    subAreas: ['Hunters Point', 'Court Square', 'Queens Plaza', 'Dutch Kills', 'Ravenswood'],
    corridors: ['Vernon Boulevard', 'Jackson Avenue', 'Queens Boulevard', '21st Street', '44th Drive'],
    transit: '7, E, M, G, N, W converge at Queens Plaza/Court Square; F at 21st St-Queensbridge',
    parkingStyle: 'high-rise-garage',
    housingType: 'high-rise glass towers, industrial conversions, fewer single-family homes than other Queens neighborhoods',
    geoAnchor: 'East River waterfront facing Manhattan, Queensboro (59th St) Bridge, LIRR Sunnyside Yard, BQE',
    responseMin: 22,
    lat: 40.7505,
    lng: -73.9405,
    restrictedNearby: ['BQE', 'Queensboro Bridge', 'RFK Bridge', 'Grand Central Parkway'],
    pattern: 'high-rise garage clearance limits service-vehicle access; weekend-warrior pattern (cars parked Friday, untouched until Monday) drains marginal batteries; auto-relock and luxury-fob lockouts common in newer towers',
    vanFitNote: 'most LIC tower garages have 6\'8" to 7\'0" clearance — confirm height when you call so we send the right vehicle',
  },

  {
    slug: 'sunnyside',
    name: 'Sunnyside',
    aliases: [],
    subAreas: ['Sunnyside Gardens', 'Sunnyside core'],
    corridors: ['Queens Boulevard', 'Greenpoint Avenue', 'Skillman Avenue', '43rd Avenue'],
    transit: '7 train along Queens Blvd (40th St-Lowery, 46th-Bliss, 52nd-Lincoln, 61st-Woodside)',
    parkingStyle: 'street-dense',
    housingType: '1920s row houses, brick walk-ups, the Sunnyside Gardens planned community (driveways/garages)',
    geoAnchor: 'between LIC and Woodside; LIRR Sunnyside Yard borders south; close to BQE',
    responseMin: 22,
    lat: 40.743,
    lng: -73.9196,
    restrictedNearby: ['BQE', 'Long Island Expressway', 'Pulaski Bridge approach'],
    pattern: '7-train commuter pattern leaves cars idle 5+ days/week; older car ownership in Sunnyside Gardens; tight street parking near Queens Boulevard',
    vanFitNote: 'standard service van fits all Sunnyside blocks',
  },

  {
    slug: 'woodside',
    name: 'Woodside',
    aliases: [],
    subAreas: ['Woodside core', 'Big Six', 'Woodside Heights'],
    corridors: ['Roosevelt Avenue', 'Queens Boulevard', 'Woodside Avenue', '61st Street', 'Northern Boulevard'],
    transit: '7 train at 61st St-Woodside (LIRR transfer); 7 elevated runs along Roosevelt Avenue',
    parkingStyle: 'street-and-driveway',
    housingType: 'mix of 1-3 family homes, walk-ups, row houses; diverse Filipino, Irish, Latino residents',
    geoAnchor: 'BQE cuts through; LIE sits just north; LIRR runs through Woodside',
    responseMin: 24,
    lat: 40.7459,
    lng: -73.9028,
    restrictedNearby: ['BQE', 'Long Island Expressway', 'Astoria Boulevard elevated sections'],
    pattern: '7-train + LIRR commuter mix; restaurants on Roosevelt Avenue draw a late-night dinner crowd that finds dead batteries at closing time',
    vanFitNote: 'standard van fits all blocks',
  },

  {
    slug: 'jackson-heights',
    name: 'Jackson Heights',
    aliases: [],
    subAreas: ['Jackson Heights Historic District', '74th Street area', 'Northern Boulevard side', 'Roosevelt Avenue side'],
    corridors: ['37th Avenue', 'Roosevelt Avenue', '74th Street', 'Northern Boulevard', '82nd Street'],
    transit: '7, E, F, M, R at 74th St-Roosevelt Ave (major hub); F at Jackson Heights-Roosevelt Ave; M/R at Northern Blvd',
    parkingStyle: 'street-dense',
    housingType: '1920s pre-war co-op buildings (historic district), brownstones, some 1-2 family homes',
    geoAnchor: 'bordered by Astoria, East Elmhurst, Corona, Elmhurst; close to LaGuardia',
    responseMin: 24,
    lat: 40.7556,
    lng: -73.883,
    restrictedNearby: ['BQE', 'Grand Central Parkway near LaGuardia', 'Northern Boulevard elevated sections'],
    pattern: 'pre-war co-op residents with older cars; 74th Street subway-hub commuter pattern; Roosevelt Avenue late-night restaurant scene; large Indian, Bangladeshi, and Latino diaspora',
    vanFitNote: 'standard van; some pre-war co-op underground garages have height limits',
  },

  {
    slug: 'east-elmhurst',
    name: 'East Elmhurst',
    aliases: [],
    subAreas: ['LaGuardia-adjacent residential', 'Ditmars side', 'North Corona border'],
    corridors: ['Astoria Boulevard', 'Northern Boulevard', '94th Street', 'Ditmars Boulevard'],
    transit: 'limited subway access; M60-SBS bus to LaGuardia; Q19, Q47, Q72 buses; nearest train is the N/W in Astoria',
    parkingStyle: 'street-and-driveway',
    housingType: '1-2 family detached and semi-detached homes, some apartment buildings',
    geoAnchor: 'borders LaGuardia Airport; Grand Central Parkway and Astoria Boulevard run through; Flushing Bay nearby',
    responseMin: 26,
    lat: 40.7635,
    lng: -73.8773,
    restrictedNearby: ['Grand Central Parkway', 'LaGuardia airport service roads', 'BQE'],
    pattern: 'airport-worker schedules and traveler pickups create round-the-clock traffic; long-time Black and Latino homeowners; LaGuardia construction has changed traffic patterns through the area',
    vanFitNote: 'standard van fits all blocks',
  },

  {
    slug: 'corona',
    name: 'Corona',
    aliases: [],
    subAreas: ['North Corona', 'Corona Heights', 'Lefrak City', 'Junction Boulevard area'],
    corridors: ['Junction Boulevard', 'Northern Boulevard', 'Roosevelt Avenue', '108th Street'],
    transit: '7 train along Roosevelt Avenue (103rd St-Corona Plaza, 111th St)',
    parkingStyle: 'street-dense',
    housingType: '1-2 family attached homes, walk-ups, Lefrak City high-rises',
    geoAnchor: 'borders Flushing Meadows-Corona Park, close to Citi Field and the USTA Billie Jean King Tennis Center',
    responseMin: 26,
    lat: 40.7444,
    lng: -73.8593,
    restrictedNearby: ['Grand Central Parkway', 'Long Island Expressway', 'Van Wyck Expressway'],
    pattern: 'large Latino population, dense walkable commercial strips; Citi Field event nights generate parking-lot calls; Roosevelt Avenue restaurant-heavy late-night activity',
    vanFitNote: 'standard van; Lefrak City underground garages have clearance limits — confirm when you call',
  },

  {
    slug: 'flushing',
    name: 'Flushing',
    aliases: [],
    subAreas: ['Downtown Flushing', 'Murray Hill', 'Linden Hill', 'Kissena', 'Auburndale'],
    corridors: ['Main Street', 'Northern Boulevard', 'Kissena Boulevard', 'Roosevelt Avenue', 'Sanford Avenue'],
    transit: '7 train terminus at Main St-Flushing; LIRR Flushing-Main St; many bus lines',
    parkingStyle: 'street-and-driveway',
    housingType: 'dense apartment buildings downtown; suburban single-family homes in Murray Hill, Linden Hill, Auburndale',
    geoAnchor: 'borders Flushing Meadows-Corona Park; Whitestone Bridge approach; LIE crosses through',
    responseMin: 28,
    lat: 40.7674,
    lng: -73.8331,
    restrictedNearby: ['Long Island Expressway', 'Whitestone Bridge approach', 'Grand Central Parkway', 'Van Wyck Expressway'],
    pattern: 'largest Asian-American population in NYC; commercial congestion in downtown Flushing; suburban quiet in Murray Hill and Linden Hill creates two very different call patterns',
    vanFitNote: 'standard van; downtown Flushing congestion can extend our arrival window slightly',
  },

  {
    slug: 'forest-hills',
    name: 'Forest Hills',
    aliases: [],
    subAreas: ['Forest Hills Gardens', 'Forest Hills core', 'Austin Street commercial', 'Rego Park border'],
    corridors: ['Austin Street', 'Queens Boulevard', 'Metropolitan Avenue', '71st Avenue/Continental Avenue'],
    transit: 'E, F, M, R at 71st-Continental Ave (major hub); LIRR Forest Hills station',
    parkingStyle: 'street-and-driveway',
    housingType: 'Forest Hills Gardens (Tudor-style mansions on private streets), pre-war co-ops along Queens Blvd, 1-2 family homes',
    geoAnchor: 'middle Queens, west of Flushing Meadows; close to USTA tennis grounds',
    responseMin: 25,
    lat: 40.7186,
    lng: -73.8466,
    restrictedNearby: ['Grand Central Parkway', 'Long Island Expressway', 'Van Wyck Expressway'],
    pattern: 'affluent demographics with older cars in pre-war co-op underground garages; Austin Street parking-lot calls common; weekend tennis events at USTA bring out-of-town drivers',
    vanFitNote: 'standard van; some pre-war co-op underground garages along Queens Blvd have low clearance',
  },

  {
    slug: 'rego-park',
    name: 'Rego Park',
    aliases: [],
    subAreas: ['Rego Park core', 'Lefrak City overlap', '63rd Drive area'],
    corridors: ['63rd Drive', 'Queens Boulevard', 'Austin Street', 'Woodhaven Boulevard', 'Yellowstone Boulevard'],
    transit: 'M, R at 63rd Drive-Rego Park; M, R at Woodhaven Blvd',
    parkingStyle: 'street-and-driveway',
    housingType: 'pre-war and post-war co-ops, Lefrak City high-rises, some 1-2 family homes on quieter blocks',
    geoAnchor: 'middle Queens',
    responseMin: 25,
    lat: 40.7273,
    lng: -73.8602,
    restrictedNearby: ['Long Island Expressway', 'Grand Central Parkway', 'Van Wyck Expressway'],
    pattern: 'large Bukharian Jewish and Russian-speaking community; older car ownership; Queens Boulevard commercial corridor calls cluster',
    vanFitNote: 'standard van; some Lefrak garage clearance limits',
  },

  {
    slug: 'briarwood',
    name: 'Briarwood',
    aliases: [],
    subAreas: ['Briarwood core', 'Hillside Avenue corridor', 'Queensboro Hill border'],
    corridors: ['Hillside Avenue', 'Main Street', 'Queens Boulevard', 'Van Wyck service road'],
    transit: 'F train at Briarwood; E, F, J, Z at nearby Jamaica-Van Wyck and Jamaica Center',
    parkingStyle: 'street-and-driveway',
    housingType: '1-2 family attached and detached homes, some apartment buildings',
    geoAnchor: 'between Forest Hills and Jamaica',
    responseMin: 28,
    lat: 40.71,
    lng: -73.8136,
    restrictedNearby: ['Van Wyck Expressway', 'Grand Central Parkway', 'Long Island Expressway'],
    pattern: 'Van Wyck airport-bound traffic creates breakdown calls on the service road; F-train Manhattan commuters; mix of South Asian, Caribbean, and African-American residents',
    vanFitNote: 'standard van fits all blocks',
  },

  {
    slug: 'jamaica',
    name: 'Jamaica',
    aliases: [],
    subAreas: ['Downtown Jamaica', 'South Jamaica', 'Jamaica Hills', 'Hollis-adjacent'],
    corridors: ['Jamaica Avenue', 'Hillside Avenue', 'Sutphin Boulevard', 'Archer Avenue', 'Liberty Avenue'],
    transit: 'E, J, Z at Jamaica Center; LIRR Jamaica Station (major hub); AirTrain to JFK',
    parkingStyle: 'street-and-driveway',
    housingType: 'dense apartment buildings, walk-ups, 1-2 family homes; mix of urban core and residential blocks',
    geoAnchor: 'south-central Queens; major transit hub (LIRR/AirTrain); near JFK',
    responseMin: 28,
    lat: 40.7026,
    lng: -73.7886,
    restrictedNearby: ['Van Wyck Expressway', 'JFK Expressway', 'Grand Central Parkway', 'Belt Parkway approach'],
    pattern: 'major transit hub creates AirTrain/LIRR traveler calls; JFK-bound traffic; large African-American, Caribbean, and South Asian populations; older car ownership in 2-family-home blocks',
    vanFitNote: 'standard van fits all blocks',
  },

  {
    slug: 'howard-beach',
    name: 'Howard Beach',
    aliases: [],
    subAreas: ['Old Howard Beach', 'New Howard Beach', 'Lindenwood', 'Hamilton Beach'],
    corridors: ['Cross Bay Boulevard', '159th Avenue', '165th Avenue'],
    transit: 'A train at Howard Beach-JFK Airport',
    parkingStyle: 'driveway-mostly',
    housingType: '1-2 family detached homes, some attached row houses; suburban feel',
    geoAnchor: 'south Queens, adjacent to JFK Airport, Jamaica Bay, Belt Parkway, Cross Bay Bridge to the Rockaways',
    responseMin: 32,
    lat: 40.6571,
    lng: -73.8417,
    restrictedNearby: ['Belt Parkway', 'Cross Bay Bridge', 'JFK Expressway', 'North Conduit Avenue'],
    pattern: 'suburban feel with longer driveways changes the typical call pattern (cars sit in driveways, not on the street); A-train + Belt Parkway commuters; long-time Italian-American community',
    vanFitNote: 'standard van; suburban driveway access easy',
  },

  {
    slug: 'ozone-park',
    name: 'Ozone Park',
    aliases: [],
    subAreas: ['Ozone Park core', 'South Ozone Park', 'Tudor Village'],
    corridors: ['Liberty Avenue', 'Rockaway Boulevard', 'Cross Bay Boulevard', '101st Avenue'],
    transit: 'A train at multiple stops along Liberty Avenue; J, Z trains nearby',
    parkingStyle: 'street-and-driveway',
    housingType: '1-2 family homes (attached and semi-attached), some apartments',
    geoAnchor: 'south Queens; near Aqueduct Racetrack/Resorts World Casino; JFK-adjacent',
    responseMin: 30,
    lat: 40.6794,
    lng: -73.8443,
    restrictedNearby: ['Belt Parkway', 'Cross Bay Boulevard restricted sections', 'North Conduit Avenue', 'JFK Expressway', 'Van Wyck Expressway'],
    pattern: 'Aqueduct/Resorts World casino traffic creates parking-lot calls at all hours; large Caribbean (Guyanese, Trinidadian) and Italian-American populations; A-train Manhattan commuters',
    vanFitNote: 'standard van fits all blocks',
  },

  {
    slug: 'richmond-hill',
    name: 'Richmond Hill',
    aliases: [],
    subAreas: ['North Richmond Hill', 'South Richmond Hill', 'Lefferts Boulevard area'],
    corridors: ['Liberty Avenue', 'Atlantic Avenue', 'Jamaica Avenue', 'Lefferts Boulevard', '101st Avenue'],
    transit: 'A train (north blocks); J, Z trains (south blocks)',
    parkingStyle: 'street-and-driveway',
    housingType: 'Victorian-era detached homes in north Richmond Hill; 1-2 family attached/detached in the south',
    geoAnchor: 'south-central Queens',
    responseMin: 28,
    lat: 40.6919,
    lng: -73.8298,
    restrictedNearby: ['Van Wyck Expressway', 'Belt Parkway', 'Atlantic Avenue restricted sections'],
    pattern: 'large Indo-Caribbean (Guyanese, Trinidadian) population in South Richmond Hill ("Little Guyana"); Sikh community presence; older Victorian homes in the north section; dense car ownership',
    vanFitNote: 'standard van fits all blocks',
  },

  {
    slug: 'maspeth',
    name: 'Maspeth',
    aliases: [],
    subAreas: ['Maspeth core', 'Industrial Maspeth', 'Frog Pond area'],
    corridors: ['Grand Avenue', 'Metropolitan Avenue', '58th Street', 'Maurice Avenue'],
    transit: 'limited subway access (M to Metropolitan Avenue is closest); bus-heavy area',
    parkingStyle: 'street-and-driveway',
    housingType: '1-2 family attached homes mixed with significant industrial and commercial corridors',
    geoAnchor: 'borders LIC, Williamsburg (Brooklyn), and Ridgewood; significant industrial area along Newtown Creek',
    responseMin: 25,
    lat: 40.7308,
    lng: -73.9097,
    restrictedNearby: ['BQE', 'Long Island Expressway', 'LIE Maspeth Bypass'],
    pattern: 'long-time working-class Polish and Italian-American community; commercial and industrial vehicles common in the call mix; tight streets near commercial sections',
    vanFitNote: 'standard van; some industrial-zone calls require careful access through narrow truck-loaded streets',
  },

  {
    slug: 'ridgewood',
    name: 'Ridgewood',
    aliases: [],
    subAreas: ['Ridgewood core', 'Glendale-adjacent', 'Bushwick (Brooklyn) border'],
    corridors: ['Myrtle Avenue', 'Forest Avenue', 'Fresh Pond Road', 'Metropolitan Avenue'],
    transit: 'M train at Forest Av, Fresh Pond Rd, Metropolitan Av; L train nearby in Bushwick',
    parkingStyle: 'street-dense',
    housingType: 'historic Mathews Model Flats row houses (1900s-1920s), 2-family attached homes, designated historic preservation district',
    geoAnchor: 'Queens-Brooklyn border with Bushwick; historic preservation district',
    responseMin: 26,
    lat: 40.7008,
    lng: -73.9078,
    restrictedNearby: ['BQE near Maspeth border', 'Cypress Hills border'],
    pattern: 'historic Mathews row-house blocks with narrow streets; gentrification mixing with long-time German, Polish, and Latino residents; L-train and M-train commuter pattern',
    vanFitNote: 'historic row-house streets are narrow — we dispatch the smaller service van',
  },

  {
    slug: 'whitestone',
    name: 'Whitestone',
    aliases: [],
    subAreas: ['Whitestone core', 'Old Whitestone', 'Beechhurst', 'Robinson Park'],
    corridors: ['14th Avenue', '150th Street', 'Cross Island Parkway service road', 'Francis Lewis Boulevard'],
    transit: 'no direct subway; Q15 and Q44 buses; closest train is the 7 line in Flushing',
    parkingStyle: 'driveway-mostly',
    housingType: '1-family suburban homes, waterfront homes in Beechhurst',
    geoAnchor: 'north Queens; Whitestone Bridge to the Bronx; East River waterfront; Cross Island Parkway',
    responseMin: 32,
    lat: 40.7867,
    lng: -73.8163,
    restrictedNearby: ['Whitestone Bridge', 'Cross Island Parkway', 'Throgs Neck Bridge approach'],
    pattern: 'suburban feel with driveways and garages; 1-family ownership; older cars sit between weekend trips; long-time Italian-American community',
    vanFitNote: 'standard van; suburban driveway access easy',
  },

  {
    slug: 'college-point',
    name: 'College Point',
    aliases: [],
    subAreas: ['College Point core', 'Whitestone-adjacent', 'Malba border'],
    corridors: ['14th Avenue', 'College Point Boulevard', '20th Avenue', '28th Avenue'],
    transit: 'no direct subway; Q25, Q65 buses serve the area',
    parkingStyle: 'driveway-mostly',
    housingType: '1-family suburban + 1-2 family attached homes',
    geoAnchor: 'north Queens; East River and Powell Cove waterfront; near Whitestone Bridge; big-box shopping zone (BJs, IKEA, Target)',
    responseMin: 32,
    lat: 40.7866,
    lng: -73.8378,
    restrictedNearby: ['Whitestone Bridge', 'Cross Island Parkway', 'Throgs Neck Bridge approach'],
    pattern: 'similar suburban character to Whitestone; big-box shopping (BJs, IKEA, Target on College Point Blvd) drives parking-lot calls; waterfront homes on Powell Cove',
    vanFitNote: 'standard van; big-box parking lot access is easy',
  },

  {
    slug: 'fresh-meadows',
    name: 'Fresh Meadows',
    aliases: [],
    subAreas: ['Fresh Meadows core', 'Hillcrest', 'Utopia', 'Cunningham Park area'],
    corridors: ['Union Turnpike', 'Horace Harding Expressway service road', '188th Street', '73rd Avenue'],
    transit: 'limited subway (E, F at Hillside Avenue stops nearby); bus-dependent area',
    parkingStyle: 'driveway-mostly',
    housingType: '1-family detached, garden apartments, the Fresh Meadows Co-op (large 1940s development), Cunningham Heights co-ops',
    geoAnchor: 'east-central Queens; borders Cunningham Park; near LIE/Grand Central Parkway junction',
    responseMin: 32,
    lat: 40.7321,
    lng: -73.7777,
    restrictedNearby: ['Long Island Expressway', 'Grand Central Parkway', 'Clearview Expressway', 'Cross Island Parkway'],
    pattern: 'Fresh Meadows Co-op apartments and Cunningham Heights co-op residents; diverse Jewish, Asian, and Latino community; LIE and Grand Central Parkway commuter pattern; older car ownership',
    vanFitNote: 'standard van fits all blocks',
  },
];
