/**
 * Cell content — tire-change × neighborhood (20 cells).
 */

module.exports = {
  astoria: {
    heroSubline: `<strong>$125 flat per service</strong>. Astoria tire-change calls are dominated by side-street parallel-parking curb damage and pothole sidewall blowouts on Astoria Boulevard service road. Older Greek and Italian family sedans on side streets between 21st Street and Steinway add steel-wheel curb-strike calls.`,
    whatIs: {
      p1: `Roadside tire-change service in Astoria swaps your flat for the spare you carry in your trunk. The work takes 20-30 minutes on site for a typical passenger car. Astoria's narrow side streets (between 21st Street and Steinway) and dense parallel-parking pattern produce more curb-strike sidewall damage than wider-street neighborhoods — drivers misjudge the curb, the sidewall takes a hit, the tire goes flat overnight. Astoria Boulevard service road is the local pothole hot spot.`,
      p2: `Astoria's vehicle mix is split between newer luxury cars at Halletts Point and Astoria Cove (often run-flats, sometimes no spare at all) and older Greek/Italian-American family sedans on the residential blocks (full-size spare in trunk, easy mount). For run-flat-equipped cars without a spare, we tow to a Queens tire shop instead of swapping. Confirm spare presence on the call so we dispatch the right resource.`,
    },
    whenToCall: [
      ['Astoria Boulevard service road pothole — sidewall blowout', 'Pothole hit at speed on the service road, sidewall bulges or splits, tire flat. Sidewall damage is unrepairable; we mount the spare.'],
      ['Side-street curb strike — parallel parking', 'Misjudged the curb while parking on a narrow side street between 21st and Steinway, sidewall took a hit, tire goes flat overnight.'],
      ['30th Avenue pothole — pre-spring freeze-thaw damage', 'Late-winter and early-spring pothole damage on 30th Avenue. Common March-April call wave.'],
      ['Halletts Point garage — flat after weekend sit', 'High-rise garage car parked Friday, flat by Sunday from a slow leak that finally went all the way down.'],
      ['Older Greek family sedan — slow leak finally flat', 'Older Astoria family sedan, traditional steel wheels, slow leak from a 6-month-old nail finally went flat.'],
      ['Cold morning low-pressure warning', 'Sub-15°F overnight, cold drops tire pressure; warning light on, tire underinflated but not flat. Top off + check for leaks.'],
    ],
    coverage: {
      intro: `Tire-change service across Astoria covers Old Astoria, Steinway, Ditmars-Steinway, Halletts Point, Astoria Cove, and Astoria Heights. Side-street access for jacking is typical; we use a heavy-duty floor jack rather than the OEM scissor jack, even on narrow Astoria blocks.`,
      why: `Astoria response is ~20 minutes average. Side-street calls require positioning the service vehicle without blocking traffic; we typically pull alongside the flat car and use the curb side for setup. Halletts Point and Astoria Cove garage calls add 5-10 minutes for garage navigation.`,
      landmarks: `Common Astoria tire-change origins: Astoria Boulevard service road (pothole damage); side streets between 21st and Steinway (curb damage); Halletts Point and Astoria Cove garage parking; 30th Avenue pothole zones; Ditmars Boulevard pre-spring freeze-thaw damage. We do not service the BQE, RFK Bridge approach, or Grand Central Parkway near LaGuardia — get off to a service road first.`,
    },
    whyHeavyDemand: `Astoria tire-change demand traces to three structural factors: (1) narrow side streets with dense parallel parking produce more curb-strike sidewall damage than wider-street neighborhoods; (2) Astoria Boulevard service road is one of Queens' rougher pothole zones, especially after the freeze-thaw cycle in late winter and early spring; (3) older daily-driver vehicles on the residential blocks have older tires (5+ years) prone to dry-rot sidewall failures.`,
    scenarios: [
      ['Astoria Boulevard pothole — Friday rush hour blowout', 'Hit a pothole at speed during the BQE-feeding rush, sidewall blew. Pulled into a side street to stop. Standard tire change.'],
      ['Side-street curb strike — Saturday parking', 'Saturday afternoon parallel parking on a Steinway-side block, curbed the wheel hard, sidewall bubble appeared.'],
      ['30th Avenue freeze-thaw pothole', 'March pothole on 30th Avenue, sidewall damage. Common late-winter call.'],
      ['Halletts Point garage — flat after the weekend', 'Slow leak from a nail picked up Friday, tire flat by Monday morning in the underground garage.'],
      ['Older Greek family sedan — dry-rot sidewall', 'Older sedan, sidewall split from age (5+ year tire dry-rotting). We mount the spare; you replace at a tire shop.'],
      ['Cold morning low-pressure warning', 'Sub-15°F, TPMS warning, tire underinflated. Top off + check for any actual leak.'],
    ],
    cellFaqs: [
      ['Do you service Halletts Point and Astoria Cove garage tire-changes?', 'Yes. Confirm garage clearance when you call (typically 6\'9" to 7\'0"). We use a low-profile floor jack that fits standard garage parking spaces.'],
      ['What if my car has run-flats and no spare?', 'Run-flats let you drive 50 miles at reduced speed after losing air. If the run-flat is destroyed, we tow to a Queens tire shop; we do not stock new tires on the service vehicle.'],
      ['Can you help on Astoria Boulevard pothole damage?', 'Yes — this is one of the most common Astoria call types. We meet you on a side street if you pulled off.'],
      ['Why are side-street curb strikes so common in Astoria?', 'Astoria has dense parallel parking on narrow side streets between 21st and Steinway. Misjudging the curb is a regular occurrence. Sidewall damage from a hard curb strike is unrepairable.'],
      ['Do you carry spares?', 'No — we mount your existing spare. If you don\'t have one, we tow to a tire shop.'],
    ],
  },

  'long-island-city': {
    heroSubline: `<strong>$125 flat per service</strong>. LIC tire-change calls split between Vernon Boulevard pothole damage, Queensboro Bridge approach blowouts, and tower-garage cars with slow leaks that went flat overnight. Luxury run-flat damage is common — we tow to a tire shop when the run-flat is destroyed.`,
    whatIs: {
      p1: `Roadside tire-change service in LIC operates in two contexts: street-level pothole-and-curb damage on Vernon Boulevard, Jackson Avenue, and the Queensboro Bridge approach feeders, and tower-garage cars discovered flat after weekend or weeklong sits. Most LIC residents drive newer luxury vehicles — BMW, Mercedes, Audi, Tesla, Volvo — many of which use run-flat tires and don't carry spares.`,
      p2: `Run-flat tires let you drive up to 50 miles at reduced speed after losing air, but once destroyed, the only fix is replacement at a tire shop. We tow to your dealer or a Queens tire shop in those cases. Cars with traditional spares get the standard swap. Garage-clearance navigation adds 5-10 minutes vs. street calls.`,
    },
    whenToCall: [
      ['Vernon Boulevard pothole — sidewall blowout', 'Hit a pothole on Vernon Boulevard near the Hunters Point waterfront, sidewall blew. Common LIC call.'],
      ['Queensboro Bridge approach — pothole damage', 'Got off the Queensboro Bridge approach onto Queens Plaza, sidewall damage from the approach lanes. We meet you on Queens Plaza or Jackson Avenue.'],
      ['Tower garage — slow leak went flat overnight', 'Picked up a nail Friday, parked in the tower garage, tire flat by Monday morning.'],
      ['Run-flat destroyed — tow required', 'Drove on the run-flat past its safe range, tire is destroyed. Tow to a dealer or tire shop.'],
      ['Court Square parking lot — debris puncture', 'Construction debris on Court Square parking lot caused a tread puncture. Standard swap.'],
      ['Cold morning low-pressure warning', 'Sub-15°F overnight, TPMS warning. Top off + check.'],
    ],
    coverage: {
      intro: `Tire-change service across Long Island City covers Hunters Point (the waterfront high-rise core), Court Square, Queens Plaza, Dutch Kills, and Ravenswood. Tower-garage navigation is typical; we use a low-profile floor jack and confirm clearance when you call.`,
      why: `LIC response is ~22 minutes average. Tower-garage check-in adds 3-5 minutes on-site (security desk, garage routing). Run-flat-only vehicles without a spare are common in LIC — confirm spare presence when you call so we dispatch the right resource.`,
      landmarks: `Common LIC tire-change origins: Vernon Boulevard pothole zones; Queensboro Bridge approach feeders; tower garage parking; Queens Plaza commercial; Jackson Avenue feeder lanes; Dutch Kills industrial-side streets. We do not service the Queensboro Bridge, BQE, or RFK Bridge approach lanes.`,
    },
    whyHeavyDemand: `LIC tire-change demand has three drivers: (1) Vernon Boulevard, Jackson Avenue, and the Queensboro Bridge approach feeders are pothole-heavy with truck traffic from Long Island and Manhattan-bound commercial vehicles; (2) tower-garage parking with weekend-and-weeklong-sit patterns produces slow-leak-now-flat call patterns where a marginal tire that was holding a slow leak gives up; (3) the high concentration of newer luxury vehicles means more run-flat tires that require tow-to-shop rather than spare-swap.`,
    scenarios: [
      ['Vernon Boulevard pothole sidewall blowout', 'Hit a pothole near the waterfront, sidewall blew, pulled into a parking spot.'],
      ['Queensboro Bridge approach pothole damage', 'Got off the bridge ramp, sidewall damage. We meet on Queens Plaza.'],
      ['Tower garage Monday morning flat', 'Slow leak picked up Friday, fully flat by Monday morning. Standard swap if there is a spare; tow if run-flat-only.'],
      ['Run-flat destroyed — tow to dealer', 'Drove on the run-flat 60+ miles, tire is destroyed. Tow to dealer.'],
      ['Court Square parking lot puncture', 'Construction debris in the lot caused a tread puncture.'],
      ['Cold morning TPMS warning', 'Sub-15°F, low-pressure light, tire underinflated. Top off + check.'],
    ],
    cellFaqs: [
      ['Do you service tower-garage tire-changes in LIC?', 'Yes. Confirm garage clearance when you call. Most LIC towers are 6\'8" to 7\'0".'],
      ['What if my car is run-flat-only with no spare?', 'We tow to your dealer or a Queens tire shop where they can sell and mount a new run-flat. Tow is included in the $125.'],
      ['Can you help on Vernon Boulevard pothole damage?', 'Yes — most common LIC call type. Pull into a parking spot off Vernon and we meet you there.'],
      ['Why are LIC luxury car flats common?', 'LIC has a high concentration of newer BMW, Mercedes, Audi, Tesla, Volvo vehicles, many on run-flat tires. Run-flats handle minor punctures but cannot be patched and must be replaced when destroyed.'],
      ['Do you carry tires for sale roadside?', 'No. We mount your existing spare or tow to a tire shop.'],
    ],
  },

  sunnyside: {
    heroSubline: `<strong>$125 flat per service</strong>. Sunnyside tire-change calls cluster around Queens Boulevard service road potholes, Skillman Avenue parallel-parking curb damage, and 7-train commuter cars discovered flat after the workweek. LIRR Sunnyside Yards adjacency adds debris-puncture calls.`,
    whatIs: {
      p1: `Roadside tire-change service in Sunnyside has a Queens Boulevard component (the service road below the 7 elevated takes a beating from truck traffic and produces sidewall blowout calls year-round) and a residential-block component (Skillman Avenue and side streets between 39th and 52nd Streets produce curb-strike damage from parallel parking and dome-light flats from cars sitting too long). 7-train commuters parked Sunday and walking back Friday occasionally find a flat from a slow leak that gave up over the workweek.`,
      p2: `Sunnyside Gardens residents — the 1920s planned-community section north of Queens Boulevard — have driveways and front-yard parking, which changes the call: less parallel-parking curb damage, more cold-morning low-pressure and slow-leak calls. Older daily-driver sedans with traditional steel wheels are common and produce more curb-damage tolerance than newer alloy-wheel cars.`,
    },
    whenToCall: [
      ['Queens Boulevard service road pothole — sidewall blowout', 'Hit a pothole at speed on the QB service road, sidewall blew.'],
      ['Skillman Avenue curb strike — parallel parking', 'Misjudged the curb while parallel parking, sidewall took a hit.'],
      ['7-train commuter return — Friday night flat', 'Parked Sunday, took the 7 to Manhattan all week, came back Friday — tire flat from a slow leak.'],
      ['Sunnyside Yards adjacent — debris puncture', 'Picked up debris (nail, screw) on a side street near the LIRR Sunnyside Yard, tire flat overnight.'],
      ['Sunnyside Gardens driveway — slow leak finally flat', 'Older sedan in the front-yard space, slow leak from a 4-month-old nail finally went flat.'],
      ['Cold morning low-pressure', 'Sub-15°F, TPMS warning, tire underinflated. Top off + check.'],
    ],
    coverage: {
      intro: `Tire-change service across Sunnyside covers Sunnyside Gardens (the historic planned community), Sunnyside core (the dense apartment blocks south of Skillman Avenue), and the Queens Boulevard commercial corridor.`,
      why: `Sunnyside response is ~22 minutes average. Side-street access for jacking is typical; the 7-train elevated structure on Queens Boulevard affects routing during peak hours.`,
      landmarks: `Common Sunnyside tire-change origins: Queens Boulevard service road (pothole damage); Skillman Avenue curb-strike side streets; Sunnyside Gardens private streets; LIRR Sunnyside Yards adjacent residential blocks; 43rd Avenue near the yard. We do not service the BQE, Long Island Expressway, or Pulaski Bridge approach.`,
    },
    whyHeavyDemand: `Sunnyside tire-change demand has three drivers: (1) Queens Boulevard service road is one of Queens\' rougher truck-and-bus traffic corridors, producing pothole sidewall blowouts year-round; (2) Skillman Avenue and side-street parallel parking produces curb-strike sidewall damage at apartment-walkup density; (3) Sunnyside Yards proximity adds debris-puncture calls on side streets where construction or yard-related debris ends up on the road.`,
    scenarios: [
      ['Queens Boulevard service road pothole', 'Hit a pothole at speed, sidewall blew. Common late-winter call.'],
      ['Skillman Avenue Saturday parking — curb strike', 'Saturday parallel parking, curbed the wheel hard, sidewall bubble.'],
      ['7-train commuter Friday flat', 'Parked Sunday, came back Friday, tire flat from a slow leak.'],
      ['Side-street near LIRR yard — nail puncture', 'Side-street parking near 43rd Avenue, picked up a nail, tire flat overnight.'],
      ['Sunnyside Gardens driveway — slow leak', 'Older sedan in front-yard parking, slow leak from a 4-month nail finally flat.'],
      ['Cold-snap TPMS warning', 'Sub-15°F, low-pressure light. Top off + check.'],
    ],
    cellFaqs: [
      ['Do you handle Queens Boulevard service road pothole damage?', 'Yes — common Sunnyside call. Pull off to a side street if you can; we meet you there.'],
      ['Are 7-train commuter return-flat calls common?', 'Yes. Cars sit on side streets Mon-Fri while owners take the 7 to Manhattan. Slow leaks that were marginal Sunday are flat by Friday.'],
      ['Do you service Sunnyside Gardens private streets?', 'Yes. Sunnyside Gardens private streets allow service-vehicle access.'],
      ['What if there\'s no spare in my older car?', 'We tow to a Queens tire shop. Most older Sunnyside cars do have full-size spares, but it\'s worth confirming when you call.'],
      ['Can you help on the BQE or LIE?', 'No. BQE and LIE main lanes are NYPD-rotation only.'],
    ],
  },

  woodside: {
    heroSubline: `<strong>$125 flat per service</strong>. Woodside tire-change calls cluster on Roosevelt Avenue pothole damage (the 7 elevated makes potholes harder to see at speed), BQE service road sidewall blowouts, and 7+LIRR commuter return flats. Big Six driveway curb damage rounds out the mix.`,
    whatIs: {
      p1: `Roadside tire-change service in Woodside operates across Roosevelt Avenue (the 7 elevated structure casts shadows that make pothole spotting harder, especially at night), the BQE service road through Woodside (rough section with frequent pothole damage), and the residential blocks. 7-train commuters and 7+LIRR commuters at 61st-Woodside park their cars Sunday and return Friday or later, often discovering slow-leak flats.`,
      p2: `Woodside has more single-family and 2-family homes than Sunnyside or Astoria, particularly around Big Six and Woodside Heights, with corresponding driveway parking. Driveway curb-damage and cold-morning low-pressure calls are common. Older daily-driver sedans on the residential blocks produce traditional-wheel curb-strike calls.`,
    },
    whenToCall: [
      ['Roosevelt Avenue pothole — under elevated', 'Hit a pothole on Roosevelt Avenue at night, didn\'t see it because of the elevated shadow. Sidewall blew.'],
      ['BQE service road — pothole sidewall blowout', 'Hit a pothole on the BQE service road through Woodside. Pulled to a side street.'],
      ['7+LIRR commuter return — flat after the week', 'Parked Sunday at 61st-Woodside, took the 7 or LIRR to Manhattan, came back Friday or later — flat tire from a slow leak.'],
      ['Big Six driveway curb damage', 'Detached or semi-detached home driveway, curbed the wheel parking in, sidewall took a hit.'],
      ['Northern Boulevard service road — pothole', 'Pothole on the Northern Boulevard service road, pulled to the shoulder for tire change.'],
      ['Cold-snap morning TPMS warning', 'Sub-15°F driveway car, low-pressure warning. Top off + check.'],
    ],
    coverage: {
      intro: `Tire-change service across Woodside covers the Woodside core (along Roosevelt Avenue and 58th-65th Streets), Big Six (the residential blocks west of Northern Boulevard), and Woodside Heights (between Northern Boulevard and the LIRR cut).`,
      why: `Woodside response is ~24 minutes average. The 7 elevated along Roosevelt Avenue affects dispatch routing — at peak hours we route via Queens Boulevard or 58th Street rather than Roosevelt directly.`,
      landmarks: `Common Woodside tire-change origins: Roosevelt Avenue under the 7 elevated; BQE service road through Woodside; 61st-Woodside transit hub side streets; Big Six driveways; Northern Boulevard service road; Queens Boulevard side streets. We do not service the BQE, Long Island Expressway, or Astoria Boulevard elevated sections — get off to a service road first.`,
    },
    whyHeavyDemand: `Woodside tire-change demand traces to three structural factors: (1) Roosevelt Avenue under the 7 elevated has poor visibility at night, making pothole avoidance harder; (2) the BQE service road through Woodside is one of Queens\' rougher pothole zones; (3) 7-train and LIRR commuter density at 61st-Woodside leaves cars sitting Mon-Fri on side streets, increasing slow-leak-now-flat patterns.`,
    scenarios: [
      ['Roosevelt Avenue elevated-shadow pothole', 'Late-night pothole hit, didn\'t see it because of the elevated structure shadow. Sidewall blew.'],
      ['BQE service road pothole sidewall blowout', 'Hit a pothole at speed on the service road. Pulled to a residential side street.'],
      ['61st-Woodside commuter Friday flat', 'Took the 7+LIRR all week, came back Friday — flat from a slow leak.'],
      ['Big Six driveway curb damage', 'Detached home driveway, curbed the wheel parking in.'],
      ['Northern Boulevard service road pothole', 'Pothole on the Northern Boulevard service road, sidewall blew.'],
      ['Cold-snap driveway TPMS warning', 'Sub-15°F driveway car, low-pressure light.'],
    ],
    cellFaqs: [
      ['Why is Roosevelt Avenue worse for tire damage?', 'The 7 elevated structure casts shadows that make pothole spotting harder at night. Late-night Roosevelt Avenue pothole hits are a regular Woodside call type.'],
      ['Do you service the BQE service road through Woodside?', 'Yes — pull off to the service road or a residential side street. We do not service the BQE main lanes (NYPD-rotation only).'],
      ['Are 7+LIRR commuter return-flat calls common?', 'Yes. Cars sit Mon-Fri while owners commute Manhattan via the 7 train or LIRR. Slow leaks gradually fully flat over a 5-7 day sit.'],
      ['Do you handle Big Six driveway calls?', 'Yes. Front-of-home access is typical.'],
      ['Can you help on the LIE main lanes?', 'No. LIE main lanes are NYPD-rotation only.'],
    ],
  },

  'jackson-heights': {
    heroSubline: `<strong>$125 flat per service</strong>. Jackson Heights tire-change calls cluster around 74th Street commuter side-street pothole damage, 82nd Street commercial corridor curb damage, Roosevelt Avenue late-night dinner-exit pothole hits, and Northern Boulevard service road. Pre-war co-op underground garage low-clearance run-flat issues add a luxury-car layer.`,
    whatIs: {
      p1: `Roadside tire-change service in Jackson Heights has a heavy commuter-and-commercial-corridor profile. The 74th Street-Roosevelt Avenue subway hub draws Manhattan commuters whose cars sit Mon-Fri on side streets, accumulating slow-leak issues that go fully flat over the workweek. 82nd Street is a dense commercial corridor with parallel parking and frequent curb-strike damage. Roosevelt Avenue's late-night dinner crowd produces pothole-hit calls when the post-dinner drive home goes through pothole damage they didn't see in the dark.`,
      p2: `Jackson Heights' pre-war co-op buildings along the Historic District have small underground garages with low clearance limits — newer luxury cars in those garages often have run-flat tires and no spare, requiring tow-to-shop rather than swap. The neighborhood's diverse demographic (Indian, Bangladeshi, Tibetan, Latin American) produces a mixed older-and-newer-car call profile.`,
    },
    whenToCall: [
      ['74th Street commuter side-street — Friday flat', 'Multi-line subway hub commuter, parked Sunday, came back Friday — flat from slow leak.'],
      ['82nd Street curb strike — parallel parking', 'Misjudged the curb while parking on 82nd Street, sidewall damage.'],
      ['Roosevelt Avenue late-night pothole', 'Hit a pothole on the late-night drive home, sidewall blew. Pulled to a side street.'],
      ['Northern Boulevard service road — pothole', 'Pothole on the Northern Boulevard service road, sidewall damage.'],
      ['Pre-war co-op underground garage — run-flat damaged', 'Newer luxury car with run-flats, tire damaged on garage entry, no spare to swap. Tow to dealer or tire shop.'],
      ['Cold-snap morning low-pressure', 'Sub-15°F, TPMS warning on commuter car.'],
    ],
    coverage: {
      intro: `Tire-change service across Jackson Heights covers the Historic District (the 1920s pre-war co-op buildings between 76th and 89th Streets), the 74th Street area, the Northern Boulevard side, and the Roosevelt Avenue commercial strip.`,
      why: `Jackson Heights response is ~24 minutes average. The 7-train and Roosevelt Avenue elevated affect dispatch routing at peak hours. Pre-war underground garages have lower clearance — confirm when you call.`,
      landmarks: `Common Jackson Heights tire-change origins: 74th Street commuter side streets; 82nd Street commercial corridor; Roosevelt Avenue (late-night pothole hits); Northern Boulevard service road; Historic District pre-war co-op underground garages. We do not service the BQE, Grand Central Parkway near LaGuardia, or Northern Boulevard elevated sections.`,
    },
    whyHeavyDemand: `Jackson Heights tire-change demand has three drivers: (1) 74th Street subway hub Manhattan-commuter density leaves cars sitting Mon-Fri on side streets, producing slow-leak-now-flat call patterns; (2) 82nd Street dense commercial parallel parking produces curb-strike sidewall damage; (3) Roosevelt Avenue late-night dinner crowd drives home through pothole zones they don\'t see in the dark.`,
    scenarios: [
      ['74th Street commuter Friday flat', 'Manhattan commuter, parked Sunday, flat by Friday from a slow leak.'],
      ['82nd Street curb strike Saturday', 'Saturday parking on 82nd, curbed the wheel.'],
      ['Roosevelt Avenue late-night pothole', 'Late-night drive home, hit a pothole, sidewall blew.'],
      ['Northern Boulevard service road pothole', 'Hit a pothole at speed, pulled to a residential side street.'],
      ['Pre-war co-op garage — run-flat damaged', 'Run-flat damaged on a pothole, no spare. Tow to dealer.'],
      ['Cold morning commuter TPMS warning', 'Sub-15°F overnight, low-pressure light.'],
    ],
    cellFaqs: [
      ['Do you handle pre-war co-op underground garage calls?', 'Yes. Pre-war garages have lower clearance (typically 6\'5"-6\'9") — confirm your specific clearance when you call so we send the right vehicle.'],
      ['Why are 74th Street commuter Friday flats common?', 'Cars sit Mon-Fri while owners commute Manhattan via the 5 lines converging at 74th Street. Slow leaks that were marginal on Sunday are fully flat by Friday.'],
      ['Are run-flats without spares common in Jackson Heights?', 'Yes — newer luxury cars (BMW, Mercedes, Audi) in the Historic District co-ops often have run-flats and no spare. We tow to a dealer or tire shop in those cases.'],
      ['Is multi-language dispatch available?', 'Dispatch is English-primary but is familiar with Hindi, Bengali, Tibetan, and Spanish neighborhood references.'],
      ['Can you help on the Roosevelt Avenue elevated?', 'You can\'t safely park on the elevated. Pull off to a side street and we meet you there.'],
    ],
  },

  'east-elmhurst': {
    heroSubline: `<strong>$125 flat per service</strong>. East Elmhurst tire-change calls cluster on Astoria Boulevard service road potholes (LaGuardia approach corridor — heavy truck traffic, severe pothole damage), driveway curb damage, and LaGuardia traveler returns finding flat tires after week-long trips. LaGuardia construction-zone debris adds nail-puncture calls.`,
    whatIs: {
      p1: `Roadside tire-change service in East Elmhurst is shaped by Astoria Boulevard adjacency. The Astoria Boulevard service road feeding LaGuardia handles heavy truck traffic — taxi fleets, hotel shuttles, food and supply deliveries to the airport, rental car returns — and the constant heavy-vehicle traffic produces severe pothole damage faster than typical residential corridors. Sidewall blowout calls on the service road are a daily occurrence.`,
      p2: `East Elmhurst residents who travel out of LaGuardia and park on residential blocks (cheaper than the LaGuardia long-term lot) often return to find a slow leak that went fully flat during the week-long sit. Older long-time-resident vehicles with older tires (5+ years) prone to dry-rot are common; the lockout pattern of older sedans + driveway parking + week-long trips means tire-change calls combine driveway curb damage with cold-morning slow-leak calls.`,
    },
    whenToCall: [
      ['Astoria Boulevard service road — pothole sidewall blowout', 'Hit a pothole on the service road, sidewall blew. Common LaGuardia-corridor call.'],
      ['LaGuardia traveler return — flat from week-long sit', 'Parked the car on a residential block before flying out, came back a week later — slow leak finally flat.'],
      ['Driveway curb damage — parking the daily-driver', 'Suburban driveway, misjudged the curb, sidewall took a hit.'],
      ['LaGuardia construction debris — nail puncture', 'Picked up a nail or screw on Astoria Boulevard near a LaGuardia construction zone.'],
      ['94th Street residential — pothole hit', 'Residential street pothole damage from freeze-thaw.'],
      ['Cold-snap morning TPMS warning', 'Sub-15°F, low-pressure light. Top off + check.'],
    ],
    coverage: {
      intro: `Tire-change service across East Elmhurst covers the LaGuardia-adjacent residential blocks (north of Astoria Boulevard between 80th and 102nd Streets), the Ditmars side, and the North Corona border.`,
      why: `East Elmhurst response is ~26 minutes average. Late-night and pre-dawn calls are typically faster because traffic is lighter. We do not enter LaGuardia airport service roads or terminal areas — those are restricted.`,
      landmarks: `Common East Elmhurst tire-change origins: Astoria Boulevard service road; residential blocks between 94th and 100th Streets; Ditmars Boulevard near the Astoria border; LaGuardia traveler parking on residential side streets. We do not service the Grand Central Parkway, LaGuardia airport service roads, or the BQE.`,
    },
    whyHeavyDemand: `East Elmhurst tire-change demand traces to three structural factors: (1) Astoria Boulevard service road handles heavy truck traffic feeding LaGuardia, producing severe pothole damage and frequent sidewall blowouts; (2) LaGuardia construction zones produce stray-nail debris that finds its way onto Astoria Boulevard side streets; (3) traveler-leaving-cars-on-residential-blocks pattern means slow-leak tires that gave up over week-long trips.`,
    scenarios: [
      ['Astoria Boulevard service road sidewall blowout', 'Hit a pothole at speed on the LaGuardia approach service road.'],
      ['Returning traveler — week-long flat', 'Parked the car before flying out, came back a week later, flat from a slow leak.'],
      ['Driveway curb damage', 'Suburban driveway parking, curbed the wheel.'],
      ['LaGuardia construction nail-puncture', 'Picked up a nail near a construction zone, tire flat overnight.'],
      ['94th Street residential pothole', 'Residential pothole, sidewall damage.'],
      ['Cold morning TPMS warning', 'Sub-15°F driveway car, low-pressure light.'],
    ],
    cellFaqs: [
      ['Do you respond to Astoria Boulevard service road pothole damage?', 'Yes — daily occurrence on the LaGuardia approach corridor.'],
      ['What about returning-traveler flat tires?', 'Common East Elmhurst call. Tell us when you returned and where you parked.'],
      ['Can you help me on the Grand Central Parkway?', 'No. Grand Central Parkway is NYPD-rotation only.'],
      ['Why is the LaGuardia corridor so rough on tires?', 'Heavy truck traffic — taxi fleets, shuttles, food deliveries, rental car returns — accelerates pothole formation. The corridor sees 4-5x normal residential truck volume.'],
      ['Do you charge more for pre-dawn calls?', 'No. $125 flat at any hour.'],
    ],
  },

  corona: {
    heroSubline: `<strong>$125 flat per service</strong>. Corona tire-change calls cluster on Roosevelt Avenue pothole damage (under the 7 elevated, hard to see at night), Citi Field game-day feeders (111th Street and Junction Boulevard), Lefrak City underground garage clearance issues, and US Open week tennis fan parking on rough side streets.`,
    whatIs: {
      p1: `Roadside tire-change service in Corona has an event-driven layer overlaid on standard residential calls. Citi Field game days bring concentrated traffic onto 111th Street and Junction Boulevard feeders, and the rough condition of those service roads produces sidewall blowouts during the post-game dispersal. US Open week brings tennis fans parking on Corona residential side streets where pothole damage is more common than the affluent neighborhoods most fans drive in from.`,
      p2: `Corona's residential character — dense 1-2 family attached homes, mostly Latin American long-time families, with older daily-driver sedans — produces standard side-street curb-strike damage and cold-morning low-pressure calls. Lefrak City underground garages add height-clearance navigation calls; older Lefrak resident sedans often have steel wheels (more curb-strike tolerance than alloys, easier swap when damaged).`,
    },
    whenToCall: [
      ['Roosevelt Avenue under 7 elevated — late-night pothole', 'Late-night drive home, hit a pothole under the elevated, sidewall blew.'],
      ['Citi Field game-day feeder — 111th Street pothole', 'Post-game traffic on 111th Street, hit a pothole at speed.'],
      ['Lefrak City underground garage — slow leak overnight', 'Picked up a nail Friday, parked in Lefrak garage, flat by Monday morning.'],
      ['US Open week — tennis fan side-street pothole', 'Late-summer Saturday, parked on a Corona residential block during a US Open match, came back to find a flat.'],
      ['Junction Boulevard pothole — sidewall blowout', 'Hit a pothole on Junction Boulevard at speed.'],
      ['Older Corona family sedan — dry-rot sidewall', 'Older sedan, 5+ year tires, dry-rot sidewall failure.'],
    ],
    coverage: {
      intro: `Tire-change service across Corona covers North Corona, Corona Heights, Lefrak City (the high-rise complex), and the Junction Boulevard commercial corridor.`,
      why: `Corona response is ~26 minutes average. Citi Field event nights and US Open week add traffic that dispatch routes around — at peak event times via the LIE service road or Northern Boulevard.`,
      landmarks: `Common Corona tire-change origins: Roosevelt Avenue (late-night pothole hits); Citi Field game-day feeders (111th Street, Junction Boulevard); Lefrak City underground garages; USTA Tennis Center event-week parking on residential blocks; 108th Street pothole zones. We do not service the Grand Central Parkway, Long Island Expressway, or Van Wyck Expressway.`,
    },
    whyHeavyDemand: `Corona tire-change demand has three drivers: (1) Roosevelt Avenue under the 7 elevated has poor visibility at night, producing late-night pothole-hit calls; (2) Citi Field game-day and US Open week traffic concentrates on rough feeder roads (111th Street, Junction Boulevard) producing event-driven sidewall blowouts; (3) older daily-driver sedans on the residential blocks have older tires (5+ years) prone to dry-rot sidewall failures.`,
    scenarios: [
      ['Roosevelt Avenue late-night pothole', 'Drove home from a Roosevelt Avenue restaurant, hit a pothole, sidewall blew.'],
      ['Citi Field game-day 111th Street feeder', 'Post-Mets-game traffic, pothole hit at speed on 111th.'],
      ['Lefrak City Monday morning flat', 'Slow leak from Friday, fully flat by Monday morning in the garage.'],
      ['US Open Saturday — tennis fan residential block', 'Late-summer Saturday, fan parked on a residential street during the match, came back to a flat.'],
      ['Junction Boulevard sidewall blowout', 'Pothole hit on Junction Boulevard at speed.'],
      ['Older sedan dry-rot failure', 'Older Corona family sedan, 5+ year tires, sidewall split from age.'],
    ],
    cellFaqs: [
      ['Do you handle Citi Field game-day tire-change calls?', 'Yes — common Corona event-driven call type. Pull off to a side street if you can; we meet you there.'],
      ['What about US Open week parking-block flats?', 'Common late-August/September. Tennis fans park on Corona residential blocks where pothole damage is more frequent than they\'re used to.'],
      ['Are Lefrak City underground garages serviceable?', 'Yes. Confirm garage clearance — typically 6\'8" to 7\'0".'],
      ['Is Spanish-speaking dispatch available?', 'Dispatch is English-primary but is familiar with Spanish neighborhood references.'],
      ['How does Corona response time compare on event nights?', '+5-8 min during Citi Field game windows and US Open week peak hours.'],
    ],
  },

  flushing: {
    heroSubline: `<strong>$125 flat per service</strong>. Flushing tire-change calls cluster on Northern Boulevard service road potholes (very rough corridor), Whitestone Bridge approach pothole damage, Main Street parking lot debris, Roosevelt Avenue elevated section damage, and Murray Hill suburban driveway curb damage.`,
    whatIs: {
      p1: `Roadside tire-change service in Flushing operates across two distinct sub-areas. Downtown Flushing — Main Street, Roosevelt Avenue, Sanford Avenue — has commercial parking lots where construction debris (nails, screws) commonly causes tread punctures. The Northern Boulevard service road through Flushing is one of Queens' rougher pothole zones and produces sidewall blowouts year-round. Whitestone Bridge approach lanes accumulate pothole damage from heavy commuter and commercial truck traffic.`,
      p2: `Murray Hill, Linden Hill, and Auburndale (the suburban side, east of Kissena Boulevard) have driveway parking and produce curb-strike damage and cold-morning low-pressure calls. Older long-time-resident sedans with steel wheels are common across both halves of Flushing; newer Korean-American family vehicles often run alloy wheels with more curb-damage sensitivity.`,
    },
    whenToCall: [
      ['Northern Boulevard service road — pothole sidewall blowout', 'Hit a pothole on the service road through Flushing. Common rough-corridor call.'],
      ['Whitestone Bridge approach — pothole damage', 'Got off the bridge approach, sidewall damage. We meet on a Flushing surface street.'],
      ['Main Street parking lot — debris puncture', 'Construction debris in a Main Street commercial parking lot, tread puncture.'],
      ['Roosevelt Avenue elevated section — pothole', 'Hit a pothole on Roosevelt Avenue, sidewall damage.'],
      ['Murray Hill suburban driveway — curb strike', 'Suburban driveway, misjudged the curb parking in.'],
      ['Older Korean-American family sedan — slow leak flat', 'Older sedan, slow leak from a 4-month nail finally went flat overnight.'],
    ],
    coverage: {
      intro: `Tire-change service across Flushing covers Downtown Flushing (the dense commercial corridor), Murray Hill (suburban single-family blocks east of Kissena Boulevard), Linden Hill, Kissena, and Auburndale.`,
      why: `Flushing response is ~28 minutes average — slightly slower than central Queens because Flushing is east of our staging zones. Downtown Flushing weekend peak congestion can extend ETA 5-10 min.`,
      landmarks: `Common Flushing tire-change origins: Northern Boulevard service road (rough pothole zone); Whitestone Bridge approach lanes; Main Street and Roosevelt Avenue parking lots (debris); Murray Hill driveways; Auburndale residential. We do not service the Long Island Expressway, Whitestone Bridge approach restricted lanes, Grand Central Parkway, or Van Wyck Expressway.`,
    },
    whyHeavyDemand: `Flushing tire-change demand has three drivers: (1) Northern Boulevard service road through Flushing is one of Queens\' worst pothole corridors, producing year-round sidewall blowouts; (2) Whitestone Bridge approach lanes accumulate pothole damage from heavy commuter and commercial truck traffic; (3) Downtown Flushing commercial parking lot construction debris (nails, screws) produces tread punctures.`,
    scenarios: [
      ['Northern Boulevard service road blowout', 'Hit a pothole at speed, sidewall blew.'],
      ['Whitestone Bridge approach pothole', 'Got off the bridge approach, sidewall damage.'],
      ['Main Street parking lot nail puncture', 'Tread puncture from construction debris in the lot.'],
      ['Roosevelt Avenue elevated pothole', 'Pothole damage on Roosevelt Avenue.'],
      ['Murray Hill driveway curb strike', 'Misjudged the curb parking in the driveway.'],
      ['Older Korean-American sedan slow leak', 'Older car, slow leak from a 4-month nail.'],
    ],
    cellFaqs: [
      ['Why is the Northern Boulevard service road so rough?', 'Heavy commuter and commercial truck traffic, plus the freeze-thaw cycle in the spring, accelerates pothole formation. Sidewall blowouts from that corridor are a daily call type.'],
      ['Do you respond to parking lot debris calls?', 'Yes. Tread punctures from construction debris in Downtown Flushing commercial lots are common. Bring the vehicle to a stable spot in the lot.'],
      ['Can you help on the Whitestone Bridge approach?', 'No — approach lanes are NYPD-rotation only. Get off to a Flushing surface street.'],
      ['Is Mandarin or Korean dispatch available?', 'Dispatch is English-primary. We work through location names in either language.'],
      ['Are Murray Hill driveway tire-changes faster?', 'Often yes — direct front-of-home access, no parking lot navigation, ~25 min vs ~28-32 min typical.'],
    ],
  },

  'forest-hills': {
    heroSubline: `<strong>$125 flat per service</strong>. Forest Hills tire-change calls cluster on Queens Boulevard service road potholes, Austin Street parallel-parking curb damage, 71st-Continental commuter return flats, and Forest Hills Gardens private street pothole damage (older streets with less repair). US Open week adds tennis fan parking-block pothole hits.`,
    whatIs: {
      p1: `Roadside tire-change service in Forest Hills operates across a wide variety of contexts. Queens Boulevard service road takes pothole damage from commercial and bus traffic. Austin Street's heavy weekend foot traffic creates parallel-parking curb-strike damage. The 71st-Continental subway hub draws Manhattan commuters whose cars sit Mon-Fri on side streets, accumulating slow-leak flats. Forest Hills Gardens — the private-street section with detached Tudor homes — has older, less-maintained streets with frequent pothole damage.`,
      p2: `Forest Hills' affluent demographic produces a mixed older-and-newer car call profile: older pre-war co-op resident sedans with steel wheels and traditional spares, alongside newer luxury vehicles with run-flats and no spare. Confirm spare presence on the call. US Open week (late August through early September) adds tennis fan parking on residential blocks unfamiliar with the local pothole zones.`,
    },
    whenToCall: [
      ['Queens Boulevard service road — pothole sidewall blowout', 'Hit a pothole at speed on the service road.'],
      ['Austin Street parallel parking — curb strike', 'Misjudged the curb parking on Austin Street, sidewall damage.'],
      ['71st-Continental commuter — Friday flat', 'Took E/F/M/R to Manhattan all week, came back Friday — flat from a slow leak.'],
      ['Forest Hills Gardens private street pothole', 'Older private-street pothole, sidewall damage on a Tudor-home driveway car.'],
      ['Pre-war co-op underground garage — run-flat damaged', 'Newer luxury car with run-flats, tire damaged on garage entry, no spare.'],
      ['US Open week — tennis fan residential block', 'Late-summer match-day, fan parked on a residential block, came back to find a flat.'],
    ],
    coverage: {
      intro: `Tire-change service across Forest Hills covers Forest Hills Gardens (the private-street Tudor section), Forest Hills core (the pre-war co-op blocks along Queens Boulevard), the Austin Street commercial corridor, and the Rego Park border.`,
      why: `Forest Hills response is ~25 minutes average. The 71st-Continental subway hub creates pedestrian density at peak hours. Pre-war underground garages have lower clearance.`,
      landmarks: `Common Forest Hills tire-change origins: Queens Boulevard service road; Austin Street parking lots and curbside; 71st-Continental commuter side streets; Forest Hills Gardens private streets; Metropolitan Avenue residential. We do not service the Grand Central Parkway, Long Island Expressway, or Van Wyck Expressway.`,
    },
    whyHeavyDemand: `Forest Hills tire-change demand has three drivers: (1) Queens Boulevard service road takes commercial and bus traffic that accelerates pothole formation; (2) Austin Street\'s dense parallel parking produces curb-strike damage at apartment-walkup density; (3) Forest Hills Gardens\' older private streets have less frequent repair and accumulate pothole damage between maintenance cycles.`,
    scenarios: [
      ['Queens Boulevard service road blowout', 'Hit a pothole at speed.'],
      ['Austin Street Saturday curb strike', 'Saturday parallel parking, curbed the wheel.'],
      ['71st-Continental commuter Friday flat', 'Manhattan commuter, flat from a slow leak after the week.'],
      ['Forest Hills Gardens pothole', 'Older private-street pothole, sidewall damage.'],
      ['Pre-war co-op run-flat damaged', 'Run-flat damaged on garage entry, no spare. Tow.'],
      ['US Open evening match — residential parking', 'Tennis fan parked on a Forest Hills block, came back to a flat.'],
    ],
    cellFaqs: [
      ['Do you service Forest Hills Gardens private streets?', 'Yes. Forest Hills Gardens private streets allow service-vehicle access for residents.'],
      ['Are pre-war co-op underground garages serviceable?', 'Yes. Pre-war garages have lower clearance — confirm when you call.'],
      ['What if my newer luxury car has run-flats and no spare?', 'We tow to a Queens tire shop or your dealer where they can sell and mount a new run-flat.'],
      ['What happens during US Open week?', 'Tennis fans parking on residential blocks bring more tire-change calls. Same flat $125, slightly slower ETA during peak match-end times.'],
      ['How does Forest Hills response compare to Rego Park?', 'About the same (~25 min) — adjacent neighborhoods.'],
    ],
  },

  'rego-park': {
    heroSubline: `<strong>$125 flat per service</strong>. Rego Park tire-change calls cluster on Queens Boulevard service road potholes, Lefrak City underground garage debris (construction nails, screws), Yellowstone Boulevard pothole damage, and 63rd Drive commercial corridor curb damage. Older Bukharian and Russian-speaking community sedans with steel wheels round out the mix.`,
    whatIs: {
      p1: `Roadside tire-change service in Rego Park has a Lefrak City component (the large 1960s high-rise complex shares parking lots and underground garages where construction debris periodically causes tread punctures) and a Queens Boulevard service-road component (truck and bus traffic accelerates pothole formation, producing year-round sidewall blowouts). 63rd Drive commercial corridor parallel parking produces curb-strike damage.`,
      p2: `The Bukharian Jewish and Russian-speaking long-time community around 63rd Drive, 99th Street, and Yellowstone Boulevard has older daily-driver sedans with steel wheels — easier curb-strike tolerance, easier spare swaps. Newer Lefrak City resident vehicles include more alloy wheels with sidewall sensitivity to potholes.`,
    },
    whenToCall: [
      ['Queens Boulevard service road — sidewall blowout', 'Hit a pothole on the service road, sidewall blew.'],
      ['Lefrak City underground garage — debris puncture', 'Picked up a nail in the Lefrak garage from construction work, tire flat overnight.'],
      ['Yellowstone Boulevard pothole — sidewall damage', 'Hit a pothole on Yellowstone Boulevard.'],
      ['63rd Drive commercial — curb strike', 'Parallel parking on 63rd Drive, curbed the wheel.'],
      ['Older Bukharian sedan — slow leak finally flat', 'Older daily-driver sedan, slow leak from a 4-month nail finally went flat.'],
      ['Cold-snap morning low-pressure', 'Sub-15°F, TPMS warning. Top off + check.'],
    ],
    coverage: {
      intro: `Tire-change service across Rego Park covers the Rego Park core (along 63rd Drive and Queens Boulevard), Lefrak City (the high-rise complex), and the 63rd Drive commercial corridor.`,
      why: `Rego Park response is ~25 minutes average. Lefrak City underground garages have specific clearance limits — confirm when you call.`,
      landmarks: `Common Rego Park tire-change origins: Queens Boulevard service road; Lefrak City underground garages; Yellowstone Boulevard pothole zones; 63rd Drive commercial; 99th Street residential blocks. We do not service the Long Island Expressway, Grand Central Parkway, or Van Wyck Expressway.`,
    },
    whyHeavyDemand: `Rego Park tire-change demand has three drivers: (1) Queens Boulevard service road truck and bus traffic accelerates pothole formation; (2) Lefrak City\'s ~5,000-unit complex shares large underground garages where construction debris produces tread punctures; (3) the older long-time-resident demographic has older tires (5+ years) prone to dry-rot sidewall failures.`,
    scenarios: [
      ['Queens Boulevard sidewall blowout', 'Hit a pothole at speed on the service road.'],
      ['Lefrak underground garage debris puncture', 'Nail picked up in the garage, tire flat overnight.'],
      ['Yellowstone Boulevard pothole', 'Hit a pothole, sidewall damage.'],
      ['63rd Drive curb strike Saturday', 'Saturday parking on 63rd Drive.'],
      ['Older Bukharian sedan slow leak', 'Older car, slow leak finally flat.'],
      ['Cold morning TPMS warning', 'Sub-15°F, low-pressure light.'],
    ],
    cellFaqs: [
      ['Are Lefrak City underground garages serviceable?', 'Yes. Confirm garage clearance (typically 6\'8" to 7\'0").'],
      ['Is Russian-speaking dispatch available?', 'Dispatch is English-primary but is familiar with Russian and Bukharian neighborhood references.'],
      ['Do you handle Queens Boulevard service road pothole damage?', 'Yes — common Rego Park call. Pull off to a side street and we meet you.'],
      ['Can you help on the LIE main lanes?', 'No. LIE main lanes are NYPD-rotation only.'],
      ['Why are Lefrak garage debris-puncture calls common?', 'The complex has periodic construction work in shared garage spaces; nails and screws find their way onto driving lanes.'],
    ],
  },

  briarwood: {
    heroSubline: `<strong>$125 flat per service</strong>. Briarwood tire-change calls cluster on Van Wyck service road potholes (heavy truck traffic = severe damage), Hillside Avenue and Main Street pothole damage, F-train station side-street pothole, and driveway-parked older car curb damage.`,
    whatIs: {
      p1: `Roadside tire-change service in Briarwood is shaped by Van Wyck Expressway adjacency. The Van Wyck service road handles heavy JFK-bound truck traffic and accumulates severe pothole damage faster than typical residential corridors. Sidewall blowout calls on the service road are a daily occurrence. Hillside Avenue and Main Street take commuter and commercial traffic that produces year-round pothole damage. The F-train Briarwood station draws Manhattan commuters whose cars sit Mon-Fri on side streets.`,
      p2: `Briarwood's residential character — 1-2 family attached and detached homes with driveway parking — produces driveway curb-strike damage and cold-morning low-pressure calls. Diverse South Asian, Caribbean, and African-American long-time residents have a mixed older-and-newer-car ownership pattern.`,
    },
    whenToCall: [
      ['Van Wyck service road — pothole sidewall blowout', 'Hit a pothole at speed on the Van Wyck service road. Common Briarwood call.'],
      ['Hillside Avenue pothole — sidewall damage', 'Hit a pothole on Hillside Avenue.'],
      ['Main Street pothole — sidewall blowout', 'Hit a pothole on Main Street.'],
      ['F-train station side street — Friday commuter flat', 'Manhattan commuter, parked Sunday near the F-train station, came back Friday — flat from a slow leak.'],
      ['Driveway curb strike — older daily-driver', 'Suburban driveway, curbed the wheel.'],
      ['Cold-snap morning TPMS warning', 'Sub-15°F driveway car, low-pressure light.'],
    ],
    coverage: {
      intro: `Tire-change service across Briarwood covers the Briarwood core (1-2 family residential blocks between the Van Wyck and Main Street, north of Hillside Avenue), the Hillside Avenue corridor, and the Queensboro Hill border.`,
      why: `Briarwood response is ~28 minutes average. Van Wyck service road traffic affects routing during peak hours and JFK rush periods.`,
      landmarks: `Common Briarwood tire-change origins: Van Wyck service road (truck-traffic pothole zone); Hillside Avenue; Main Street; F-train Briarwood station side streets; residential blocks between Van Wyck and Main Street. We do not service the Van Wyck Expressway main lanes, Grand Central Parkway, or Long Island Expressway.`,
    },
    whyHeavyDemand: `Briarwood tire-change demand has three drivers: (1) Van Wyck service road handles JFK-bound truck traffic that accelerates pothole formation, producing daily sidewall blowouts; (2) Hillside Avenue and Main Street commercial-corridor traffic produces year-round pothole damage; (3) F-train Manhattan-commuter pattern leaves cars sitting Mon-Fri, increasing slow-leak-now-flat calls.`,
    scenarios: [
      ['Van Wyck service road sidewall blowout', 'Hit a pothole at speed on the service road.'],
      ['Hillside Avenue pothole sidewall damage', 'Pothole hit on Hillside Avenue.'],
      ['Main Street pothole', 'Pothole damage on Main Street.'],
      ['F-train commuter Friday flat', 'Manhattan commuter, slow leak gone fully flat by Friday.'],
      ['Driveway curb strike', 'Suburban driveway curb damage.'],
      ['Cold-snap TPMS warning', 'Sub-15°F driveway car, low-pressure light.'],
    ],
    cellFaqs: [
      ['Why is the Van Wyck service road so rough on tires?', 'JFK-bound truck traffic — cargo trucks, fuel tankers, food and supply deliveries to the airport — accelerates pothole formation. The service road sees 4-5x normal residential truck volume.'],
      ['Do you service the Van Wyck Expressway main lanes?', 'No. Van Wyck main lanes are NYPD-rotation only. Get off to the service road.'],
      ['Are F-train commuter Friday flats common?', 'Yes — cars sit Mon-Fri on side streets near the Briarwood F station. Slow leaks accumulate fully flat over the workweek.'],
      ['How does Briarwood response compare to Jamaica?', 'Both ~28 min — adjacent neighborhoods.'],
      ['Can you help on Hillside Avenue pothole damage?', 'Yes. Pull to a side street if you can.'],
    ],
  },

  jamaica: {
    heroSubline: `<strong>$125 flat per service</strong>. Jamaica tire-change calls cluster on Sutphin Boulevard pothole damage (especially the AirTrain feeder zone), Archer Avenue service road potholes, Jamaica Avenue commercial corridor damage, and AirTrain-traveler-return flats from week-long sits.`,
    whatIs: {
      p1: `Roadside tire-change service in Jamaica is shaped by transit-hub geography. Sutphin Boulevard between the LIRR Jamaica Station and the AirTrain station handles heavy traveler and commercial traffic — taxi and rideshare fleets, food deliveries, AirTrain commuter buses — and accumulates pothole damage faster than residential corridors. Archer Avenue and Jamaica Avenue see constant commercial-vehicle traffic. The AirTrain traveler pattern (parking on Jamaica residential blocks for multi-day trips) produces returning-with-flat tire calls.`,
      p2: `Jamaica's diverse long-time-resident demographic — African-American, Caribbean, South Asian families — produces a typical mixed older-and-newer-car call profile. Older daily-driver sedans on the South Jamaica and Jamaica Hills residential blocks have steel wheels and traditional spares; newer immigrant family vehicles include more alloy wheels and run-flats.`,
    },
    whenToCall: [
      ['Sutphin Boulevard — AirTrain feeder pothole', 'Hit a pothole on Sutphin Boulevard near the AirTrain feeder zone. Sidewall damage.'],
      ['Archer Avenue service road — pothole', 'Hit a pothole on the Archer Avenue service road, sidewall blew.'],
      ['Jamaica Avenue commercial pothole', 'Pothole damage on Jamaica Avenue.'],
      ['AirTrain returning traveler — week-long flat', 'Parked the car on a Jamaica residential block before flying out, came back a week later — slow leak finally flat.'],
      ['South Jamaica residential — older daily-driver dry-rot', 'Older sedan, 5+ year tires, dry-rot sidewall failure.'],
      ['Hillside Avenue commercial pothole', 'Pothole on Hillside Avenue, sidewall damage.'],
    ],
    coverage: {
      intro: `Tire-change service across Jamaica covers Downtown Jamaica (around Jamaica Center, Sutphin Boulevard, and Archer Avenue), South Jamaica, Jamaica Hills, and the Hollis-adjacent border.`,
      why: `Jamaica response is ~28 minutes average. Sutphin Boulevard AirTrain and LIRR feeder traffic during JFK rush periods can add 2-3 min.`,
      landmarks: `Common Jamaica tire-change origins: Sutphin Boulevard (AirTrain feeder pothole zone); Archer Avenue service road; Jamaica Avenue commercial; South Jamaica residential blocks; Jamaica Hills elevated residential. We do not service the Van Wyck Expressway, JFK Expressway, Grand Central Parkway, or Belt Parkway approach.`,
    },
    whyHeavyDemand: `Jamaica tire-change demand has three drivers: (1) Sutphin Boulevard AirTrain feeder zone handles heavy traveler and commercial traffic that accelerates pothole formation; (2) Archer Avenue and Jamaica Avenue commercial-corridor traffic produces year-round damage; (3) AirTrain traveler pattern produces returning-with-flat calls from cars parked on residential blocks during multi-day trips.`,
    scenarios: [
      ['Sutphin Boulevard AirTrain pothole', 'Hit a pothole near the AirTrain feeder, sidewall damage.'],
      ['Archer Avenue service road blowout', 'Pothole at speed on Archer Avenue service road.'],
      ['Jamaica Avenue commercial pothole', 'Pothole damage on Jamaica Avenue.'],
      ['Returning AirTrain traveler — week flat', 'Parked before flying out, returned to a flat from a slow leak.'],
      ['South Jamaica older sedan dry-rot', 'Older car, 5+ year tires, sidewall split from age.'],
      ['Hillside Avenue commercial pothole', 'Hit a pothole on Hillside Avenue.'],
    ],
    cellFaqs: [
      ['Do you respond to AirTrain-traveler tire-change calls?', 'Yes — common Jamaica call. Tell us when you returned, where you parked, vehicle make/model.'],
      ['Why is Sutphin Boulevard so rough on tires?', 'Heavy traveler and commercial traffic — taxi and rideshare fleets, AirTrain buses, food deliveries — accelerates pothole formation.'],
      ['Can you help on the Van Wyck Expressway or JFK Expressway?', 'No. Van Wyck, JFK Expressway, and Belt Parkway are NYPD-rotation only.'],
      ['Is multi-language dispatch available?', 'Dispatch is English-primary but is familiar with Spanish, Urdu, Bengali, and Caribbean-English neighborhood references.'],
      ['Do you handle Jamaica Avenue commercial corridor calls?', 'Yes. Pull to a side street if you can.'],
    ],
  },

  'howard-beach': {
    heroSubline: `<strong>$125 flat per service</strong>. Howard Beach tire-change calls cluster on Cross Bay Boulevard pothole damage, Belt Parkway service road potholes, suburban driveway curb damage, and Hamilton Beach waterfront salt-air-accelerated tire dry-rot. Response time is ~32 min because Howard Beach sits at the south edge of Queens.`,
    whatIs: {
      p1: `Roadside tire-change service in Howard Beach has a suburban character distinct from the rest of Queens. Most homes are 1-family detached with driveway parking, which changes the call mix: more driveway curb-strike damage and cold-morning low-pressure calls than dense apartment-walkup neighborhoods. Cross Bay Boulevard heading to the Rockaways takes commuter and seasonal traffic that produces pothole damage year-round, especially on the bridge approach.`,
      p2: `Hamilton Beach is the small waterfront pocket adjacent to Jamaica Bay. Salt-air corrosion accelerates tire degradation — older tires (5+ years) on cars parked near the water have dry-rot sidewall failures more often than inland Queens tires. Older Italian-American long-time-family multi-car households often have an older third or fourth car with aging tires that fail under load.`,
    },
    whenToCall: [
      ['Cross Bay Boulevard pothole — sidewall blowout', 'Hit a pothole on Cross Bay Boulevard. Common Howard Beach call.'],
      ['Belt Parkway service road — pothole damage', 'Pothole on the Belt Parkway service road, sidewall blew.'],
      ['Suburban driveway curb strike', 'Misjudged the curb pulling into the driveway.'],
      ['Hamilton Beach waterfront — salt-air dry-rot sidewall', 'Older car parked near Jamaica Bay, sidewall split from salt-air-accelerated dry-rot.'],
      ['A-train Howard Beach-JFK station — Friday commuter flat', 'A-train commuter parked Sunday near the station, came back Friday — flat from a slow leak.'],
      ['Older Italian-American family sedan — dry-rot', 'Multi-car household third or fourth car, older tires, dry-rot sidewall failure.'],
    ],
    coverage: {
      intro: `Tire-change service across Howard Beach covers Old Howard Beach, New Howard Beach, Lindenwood, and Hamilton Beach (the waterfront pocket).`,
      why: `Howard Beach response is ~32 minutes average — longer than most Queens neighborhoods because of the south-edge geography. Belt Parkway and Cross Bay Boulevard rush-hour traffic affects routing.`,
      landmarks: `Common Howard Beach tire-change origins: Cross Bay Boulevard (commuter and seasonal traffic pothole damage); Belt Parkway service road; Old and New Howard Beach driveways; Hamilton Beach waterfront (salt-air dry-rot); A-train Howard Beach-JFK station side streets. We do not service the Belt Parkway, Cross Bay Bridge, JFK Expressway, or North Conduit Avenue.`,
    },
    whyHeavyDemand: `Howard Beach tire-change demand has three drivers: (1) Cross Bay Boulevard takes commuter and seasonal Rockaway-bound traffic producing year-round pothole damage; (2) Hamilton Beach waterfront salt-air accelerates tire dry-rot on older cars parked near Jamaica Bay; (3) suburban multi-car households often keep older third or fourth cars with aging tires that fail under load.`,
    scenarios: [
      ['Cross Bay Boulevard pothole', 'Hit a pothole at speed, sidewall blew.'],
      ['Belt Parkway service road pothole', 'Pothole on the service road, sidewall damage.'],
      ['Suburban driveway curb strike', 'Misjudged the curb on the driveway.'],
      ['Hamilton Beach salt-air dry-rot', 'Older car, sidewall split from salt-air degradation.'],
      ['A-train commuter Friday flat', 'Parked Sunday at Howard Beach-JFK station, flat by Friday.'],
      ['Older multi-car household sedan dry-rot', 'Third or fourth car, aging tires, dry-rot sidewall.'],
    ],
    cellFaqs: [
      ['Why is Howard Beach response time longer?', 'Howard Beach sits at the south edge of Queens, far from our north-Queens staging zones. ~32 min vs ~20 min Astoria.'],
      ['Can you help on Cross Bay Bridge or Belt Parkway?', 'No. Cross Bay Bridge, Belt Parkway, JFK Expressway, and North Conduit Avenue are NYPD-rotation only.'],
      ['Are Hamilton Beach waterfront calls common?', 'Yes. Salt-air-accelerated dry-rot is a real factor on older cars parked near Jamaica Bay.'],
      ['Do you handle suburban driveway calls?', 'Yes. Direct front-of-home access typical.'],
      ['What if my older car has a 5+ year-old spare in the trunk?', 'Older spares can have dry-rot too. We inspect before mounting; if the spare is also dry-rotted, we tow to a tire shop.'],
    ],
  },

  'ozone-park': {
    heroSubline: `<strong>$125 flat per service</strong>. Ozone Park tire-change calls cluster on Aqueduct/Resorts World casino lot debris (construction nails), Liberty Avenue pothole damage, Cross Bay Boulevard pothole, and Rockaway Boulevard. A-train station commuter return flats add to the mix.`,
    whatIs: {
      p1: `Roadside tire-change service in Ozone Park has a 24-hour casino-driven layer overlaid on standard residential calls. Resorts World Casino at Aqueduct has periodic construction work in shared parking lots, and stray nails and screws find their way onto driving lanes — tread punctures from casino lot debris are a regular call type. Liberty Avenue and Rockaway Boulevard take commuter and commercial traffic that produces pothole damage year-round.`,
      p2: `Ozone Park's residential character — dense 1-2 family attached homes, dominantly Caribbean (Guyanese, Trinidadian) and Italian-American long-time residents — produces a typical mixed-vehicle call profile. Older daily-driver sedans on residential blocks have older tires prone to dry-rot. A-train Manhattan commuters parked on side streets near Liberty Avenue stations leave cars sitting Mon-Fri.`,
    },
    whenToCall: [
      ['Resorts World Casino lot — construction nail puncture', 'Picked up a nail in the casino parking lot from construction debris, tread puncture.'],
      ['Liberty Avenue pothole — sidewall blowout', 'Hit a pothole on Liberty Avenue at speed.'],
      ['Cross Bay Boulevard pothole', 'Pothole damage on Cross Bay Boulevard.'],
      ['Rockaway Boulevard pothole', 'Pothole on Rockaway Boulevard.'],
      ['A-train Liberty Avenue commuter — Friday flat', 'A-train commuter parked Sunday on a side street, flat by Friday from a slow leak.'],
      ['Older daily-driver — dry-rot sidewall', 'Older Ozone Park family sedan, 5+ year tires, dry-rot failure.'],
    ],
    coverage: {
      intro: `Tire-change service across Ozone Park covers the Ozone Park core (along Liberty Avenue and Rockaway Boulevard), South Ozone Park, and Tudor Village.`,
      why: `Ozone Park response is ~30 minutes average. Aqueduct/Resorts World event traffic during major event nights and weekend peak hours can add 5-8 minutes.`,
      landmarks: `Common Ozone Park tire-change origins: Aqueduct/Resorts World casino parking lot; Liberty Avenue commercial corridor; Cross Bay Boulevard; Rockaway Boulevard; A-train Liberty Avenue station side streets; 101st Avenue residential. We do not service the Belt Parkway, Cross Bay Boulevard restricted sections, North Conduit Avenue, JFK Expressway, or Van Wyck Expressway.`,
    },
    whyHeavyDemand: `Ozone Park tire-change demand has three drivers: (1) Resorts World Casino periodic construction debris in shared parking lots produces tread punctures at all hours; (2) Liberty Avenue, Cross Bay Boulevard, and Rockaway Boulevard handle commuter and commercial-vehicle traffic that produces year-round pothole damage; (3) older daily-driver vehicles in the Caribbean and Italian-American long-time-resident community have older tires prone to dry-rot sidewall failures.`,
    scenarios: [
      ['Resorts World casino lot nail puncture', 'Tread puncture from construction debris.'],
      ['Liberty Avenue pothole blowout', 'Hit a pothole at speed.'],
      ['Cross Bay Boulevard pothole', 'Pothole damage on Cross Bay Boulevard.'],
      ['Rockaway Boulevard pothole', 'Pothole on Rockaway Boulevard.'],
      ['A-train commuter Friday flat', 'Parked Sunday on a side street, flat by Friday.'],
      ['Older daily-driver dry-rot', 'Older Ozone Park sedan, sidewall split from age.'],
    ],
    cellFaqs: [
      ['Do you respond to Resorts World casino lot tire-changes?', 'Yes — 24/7. Casino lot is in coverage. Tell us your row and vehicle make/model.'],
      ['Why are casino lot debris-puncture calls common?', 'Periodic construction work in shared parking lots leaves stray nails and screws on driving lanes.'],
      ['Can you help on the Belt Parkway or North Conduit?', 'No. Belt Parkway, North Conduit Avenue, JFK Expressway, and Cross Bay Boulevard restricted sections are NYPD-rotation only.'],
      ['Is multi-language dispatch available?', 'Dispatch is English-primary but is familiar with Caribbean-English, Spanish, and Italian neighborhood references.'],
      ['How does Ozone Park response compare to Howard Beach?', '~30 min Ozone Park vs ~32 min Howard Beach.'],
    ],
  },

  'richmond-hill': {
    heroSubline: `<strong>$125 flat per service</strong>. Richmond Hill tire-change calls cluster on Liberty Avenue pothole damage (especially South RH commercial corridor), South RH dense street parking curb damage, Lefferts Boulevard pothole, and North RH Victorian streets (older asphalt with less repair). Atlantic Avenue rough sections add highway-corridor pothole damage.`,
    whatIs: {
      p1: `Roadside tire-change service in Richmond Hill operates across two distinct sub-areas. South Richmond Hill — "Little Guyana" — has dense Indo-Caribbean and Sikh community foot traffic on Liberty Avenue, with corresponding parking density and curb-strike damage. The Liberty Avenue corridor also takes commercial-vehicle traffic from the gurdwaras, restaurants, and shops, producing pothole damage year-round.`,
      p2: `North Richmond Hill, with its Victorian-era detached homes from the late 1800s and early 1900s, has older private streets and less frequent municipal repair than newer Queens neighborhoods. Pothole damage accumulates between maintenance cycles. Older Victorian-home driveways often have curb-strike damage from unfamiliar visitors. Lefferts Boulevard runs through both halves, producing both kinds of calls.`,
    },
    whenToCall: [
      ['Liberty Avenue pothole — South RH commercial', 'Hit a pothole on Liberty Avenue in South Richmond Hill, sidewall damage.'],
      ['Lefferts Boulevard pothole', 'Pothole on Lefferts Boulevard, sidewall damage.'],
      ['North Richmond Hill Victorian street pothole', 'Older private-street pothole damage from less-frequent repair.'],
      ['South Richmond Hill curb strike — dense parking', 'Parallel parking on a Liberty Avenue side street, curbed the wheel.'],
      ['Atlantic Avenue rough section pothole', 'Pothole on Atlantic Avenue near the Brooklyn border, sidewall damage.'],
      ['Older homeowner family sedan — dry-rot', 'Older sedan, 5+ year tires, dry-rot sidewall failure.'],
    ],
    coverage: {
      intro: `Tire-change service across Richmond Hill covers North Richmond Hill (the Victorian-era detached-home blocks), South Richmond Hill ("Little Guyana"), and the Lefferts Boulevard corridor.`,
      why: `Richmond Hill response is ~28 minutes average. South Richmond Hill's dense parking and pedestrian density along Liberty Avenue can add 2-3 min during peak commercial hours.`,
      landmarks: `Common Richmond Hill tire-change origins: Liberty Avenue commercial corridor; Lefferts Boulevard; North Richmond Hill Victorian streets; Atlantic Avenue rough sections; 101st Avenue/Jamaica Avenue commercial. We do not service the Van Wyck Expressway, Belt Parkway, or Atlantic Avenue restricted sections.`,
    },
    whyHeavyDemand: `Richmond Hill tire-change demand has three drivers: (1) Liberty Avenue\'s dense commercial and residential parking produces curb-strike damage at apartment-walkup density; (2) North Richmond Hill\'s older Victorian-era streets have less frequent municipal repair, accumulating pothole damage between maintenance cycles; (3) Atlantic Avenue rough sections near the Brooklyn border produce highway-corridor pothole damage.`,
    scenarios: [
      ['Liberty Avenue pothole — South RH commercial', 'Hit a pothole on Liberty Avenue in South Richmond Hill.'],
      ['Lefferts Boulevard pothole', 'Pothole on Lefferts Boulevard.'],
      ['North Richmond Hill Victorian street pothole', 'Older private street pothole damage.'],
      ['South Richmond Hill curb strike', 'Parallel parking, curbed the wheel.'],
      ['Atlantic Avenue rough section', 'Pothole near the Brooklyn border.'],
      ['Older homeowner sedan dry-rot', 'Older car, 5+ year tires, sidewall split.'],
    ],
    cellFaqs: [
      ['Do you serve South Richmond Hill ("Little Guyana")?', 'Yes — South Richmond Hill is in coverage. Liberty Avenue commercial and the residential side streets are all serviceable.'],
      ['Is multi-language dispatch available?', 'Dispatch is English-primary but is familiar with Punjabi, Hindi, Caribbean-English, and Spanish neighborhood references.'],
      ['Why do North Richmond Hill streets have more pothole damage?', 'Older Victorian-era streets have less frequent municipal repair than newer Queens neighborhoods. Damage accumulates between cycles.'],
      ['Can you help on Atlantic Avenue itself?', 'Atlantic Avenue surface lanes — yes. Restricted sections — no.'],
      ['How does Richmond Hill response compare to Jamaica?', 'Both ~28 min — adjacent neighborhoods.'],
    ],
  },

  maspeth: {
    heroSubline: `<strong>$125 flat per service</strong>. Maspeth tire-change calls cluster on BQE service road pothole damage (very rough corridor), Newtown Creek industrial corridor debris-puncture (nails, screws from warehouses), Grand Avenue pothole, and commercial fleet vehicle flats. Older daily-driver dry-rot rounds out the residential mix.`,
    whatIs: {
      p1: `Roadside tire-change service in Maspeth has two distinct profiles: residential calls on the dense 1-2 family blocks (Polish and Italian-American long-time families with older daily-driver sedans), and commercial-fleet calls in the Newtown Creek industrial corridor along Grand Avenue and 58th Street. Light-duty commercial vehicles — delivery vans, box trucks under 26k GVWR, light pickups — get flats from warehouse loading-bay debris regularly.`,
      p2: `The BQE service road through Maspeth is one of Queens\' rougher pothole zones. Heavy truck traffic from the LIE feeders and Newtown Creek industrial corridor accelerates pothole formation. Sidewall blowouts on the BQE service road are a daily call type. Older Maspeth daily-driver sedans on residential blocks have aging tires (5+ years) prone to dry-rot.`,
    },
    whenToCall: [
      ['BQE service road — pothole sidewall blowout', 'Hit a pothole on the BQE service road through Maspeth. Common rough-corridor call.'],
      ['Newtown Creek industrial corridor — debris puncture', 'Picked up a nail or screw at a warehouse loading bay, tread puncture.'],
      ['Grand Avenue pothole — sidewall damage', 'Pothole on Grand Avenue.'],
      ['Commercial fleet vehicle — flat', 'Light-duty commercial pickup or delivery van, flat at a Newtown Creek warehouse.'],
      ['Older daily-driver — dry-rot sidewall', 'Older Polish or Italian-American family sedan, 5+ year tires, dry-rot failure.'],
      ['Metropolitan Avenue pothole', 'Pothole on Metropolitan Avenue, sidewall damage.'],
    ],
    coverage: {
      intro: `Tire-change service across Maspeth covers the Maspeth core (dense 1-2 family residential), Industrial Maspeth (warehouse-and-manufacturing along Newtown Creek), and the Frog Pond area.`,
      why: `Maspeth response is ~25 minutes average. Industrial corridor traffic during business hours can affect routing.`,
      landmarks: `Common Maspeth tire-change origins: BQE service road; Newtown Creek industrial corridor (warehouse debris); Grand Avenue; Metropolitan Avenue; 58th Street and Maurice Avenue commercial. We do not service the BQE main lanes, Long Island Expressway main lanes, or LIE Maspeth Bypass.`,
    },
    whyHeavyDemand: `Maspeth tire-change demand has three drivers: (1) BQE service road handles heavy truck traffic from the LIE feeders, accelerating pothole formation; (2) Newtown Creek industrial corridor warehouses periodically have construction debris (nails, screws) that ends up on driving lanes; (3) older Polish and Italian-American long-time-family daily-driver sedans on residential blocks have older tires prone to dry-rot.`,
    scenarios: [
      ['BQE service road sidewall blowout', 'Hit a pothole at speed.'],
      ['Industrial corridor debris puncture', 'Nail picked up at a warehouse loading bay.'],
      ['Grand Avenue pothole', 'Pothole on Grand Avenue.'],
      ['Commercial fleet vehicle flat', 'Light-duty pickup at a Newtown Creek warehouse.'],
      ['Older daily-driver dry-rot', 'Older family sedan, sidewall split from age.'],
      ['Metropolitan Avenue pothole', 'Pothole on Metropolitan Avenue.'],
    ],
    cellFaqs: [
      ['Do you handle commercial fleet tire-changes in Maspeth?', 'Yes — light-duty commercial up to 26k GVWR (delivery vans, box trucks, light pickups). Heavy commercial we cannot service.'],
      ['Why is the BQE service road through Maspeth so rough?', 'Heavy truck traffic from the LIE feeders and Newtown Creek industrial corridor accelerates pothole formation.'],
      ['Are warehouse debris-puncture calls common?', 'Yes. Periodic construction work in industrial-zone warehouses leaves stray nails and screws on driving lanes.'],
      ['Can you help on the BQE main lanes?', 'No. BQE main lanes are NYPD-rotation only. Get off to Grand Avenue or Metropolitan Avenue.'],
      ['Is Polish-language dispatch available?', 'Dispatch is English-primary but is familiar with Polish neighborhood references.'],
    ],
  },

  ridgewood: {
    heroSubline: `<strong>$125 flat per service</strong>. Ridgewood tire-change calls cluster on Mathews row-house street curb damage (narrow streets, parallel parking), Myrtle Avenue pothole, M-train Forest Avenue area pothole, and Bushwick border block pothole damage (older asphalt, less repair).`,
    whatIs: {
      p1: `Roadside tire-change service in Ridgewood operates on streets designed in the 1900s. The Mathews Model Flats — historic 2-family row houses — line many Ridgewood blocks with party-wall construction and 18-foot-wide streets, with parallel parking on both sides. Curb-strike sidewall damage from those tight streets is a Ridgewood signature call type. The smaller service van is standard for Ridgewood dispatch.`,
      p2: `Myrtle Avenue commercial corridor takes M-train station feeder traffic and produces pothole damage year-round. The Bushwick (Brooklyn) border blocks have older asphalt with less frequent repair than central Queens. M-train Forest Avenue, Fresh Pond, and Metropolitan Avenue station areas draw commuters whose cars sit Mon-Fri on side streets.`,
    },
    whenToCall: [
      ['Mathews row-house street — curb strike', 'Misjudged the curb on a narrow row-house street, sidewall damage.'],
      ['Myrtle Avenue pothole — sidewall blowout', 'Hit a pothole on Myrtle Avenue.'],
      ['M-train Forest Avenue area pothole', 'Pothole near the M-train Forest Avenue station, sidewall damage.'],
      ['Bushwick border block — old asphalt pothole', 'Pothole on a Bushwick-border block (older asphalt, less repair).'],
      ['Older daily-driver — dry-rot sidewall', 'Long-time Polish or German family sedan, 5+ year tires, dry-rot failure.'],
      ['Cold-snap morning — TPMS warning', 'Sub-15°F overnight, low-pressure light.'],
    ],
    coverage: {
      intro: `Tire-change service across Ridgewood covers the Ridgewood core (the historic Mathews row-house blocks), Glendale-adjacent, and the Bushwick (Brooklyn) border.`,
      why: `Ridgewood response is ~26 minutes average. Narrow historic row-house streets require the smaller service van. The 18-foot-wide row-house streets with parallel parking on both sides require careful service-vehicle positioning.`,
      landmarks: `Common Ridgewood tire-change origins: Mathews Model Flats row-house blocks; Myrtle Avenue commercial corridor; M-train Forest Avenue station area; Fresh Pond Road residential; Bushwick (Brooklyn) border blocks. We do not service the BQE near the Maspeth border or Cypress Hills border restricted sections.`,
    },
    whyHeavyDemand: `Ridgewood tire-change demand has three drivers: (1) historic row-house streets have heavy parallel-parking density on narrow streets, producing curb-strike sidewall damage at apartment-walkup density; (2) Myrtle Avenue commercial corridor takes M-train station feeder traffic, producing year-round pothole damage; (3) Bushwick-border blocks have older asphalt with less frequent municipal repair, accumulating pothole damage between cycles.`,
    scenarios: [
      ['Mathews row-house curb strike', 'Misjudged the curb, sidewall damage.'],
      ['Myrtle Avenue pothole blowout', 'Hit a pothole on Myrtle Avenue.'],
      ['M-train Forest Avenue pothole', 'Pothole near the station.'],
      ['Bushwick border pothole', 'Pothole on a border block (older asphalt).'],
      ['Older daily-driver dry-rot', 'Long-time Polish family sedan, sidewall split.'],
      ['Cold morning TPMS warning', 'Sub-15°F, low-pressure light.'],
    ],
    cellFaqs: [
      ['Why does Ridgewood require a smaller service van?', 'Mathews Model Flats row-house streets are 18 feet wide with double-parked cars on both sides. The smaller van is standard for Ridgewood.'],
      ['Do you serve Bushwick-border Ridgewood blocks?', 'Yes — Wyckoff Avenue and St Nicholas Avenue blocks are in Ridgewood coverage. We do not cross into Bushwick proper.'],
      ['Is Polish or German dispatch available?', 'Dispatch is English-primary but is familiar with Polish references.'],
      ['Are most Ridgewood tire-changes traditional steel-wheel cars?', 'A high proportion — long-time German, Polish, and Latino families with older daily-driver sedans.'],
      ['How does Ridgewood response compare to Maspeth?', '~26 min vs ~25 min — adjacent neighborhoods.'],
    ],
  },

  whitestone: {
    heroSubline: `<strong>$125 flat per service</strong>. Whitestone tire-change calls run on suburban driveway rhythms — Cross Island Parkway service road potholes, Whitestone Bridge approach pothole damage, suburban driveway curb strikes, and Beechhurst waterfront salt-air-accelerated tire dry-rot. Response time is ~32 min.`,
    whatIs: {
      p1: `Roadside tire-change service in Whitestone operates in a suburban environment. Most homes are 1-family detached with driveway parking, which changes the call mix: more driveway curb-strike damage and cold-morning low-pressure calls than dense apartment neighborhoods. Cross Island Parkway service road takes commuter traffic and produces pothole damage year-round. Whitestone Bridge approach lanes accumulate pothole damage from heavy commuter and commercial truck traffic.`,
      p2: `Beechhurst is the small waterfront pocket on the East River side of Whitestone. Salt-air corrosion accelerates tire degradation — older tires (5+ years) on cars parked near the water have dry-rot sidewall failures more often than inland Whitestone. Older Italian-American long-time-family multi-car households often have older third or fourth cars with aging tires.`,
    },
    whenToCall: [
      ['Cross Island Parkway service road — pothole sidewall blowout', 'Hit a pothole on the Cross Island service road.'],
      ['Whitestone Bridge approach — pothole damage', 'Got off the bridge approach, sidewall damage. We meet on a Whitestone surface street.'],
      ['Suburban driveway curb strike', 'Misjudged the curb pulling into the driveway.'],
      ['Beechhurst waterfront — salt-air dry-rot sidewall', 'Older car parked near the East River, sidewall split from salt-air-accelerated dry-rot.'],
      ['Older Italian-American family sedan — dry-rot', 'Multi-car household third or fourth car, older tires, dry-rot sidewall.'],
      ['14th Avenue pothole — sidewall damage', 'Pothole on 14th Avenue.'],
    ],
    coverage: {
      intro: `Tire-change service across Whitestone covers Whitestone core (between 14th Avenue and the Cross Island Parkway), Old Whitestone, Beechhurst (the waterfront pocket), and Robinson Park.`,
      why: `Whitestone response is ~32 minutes average — longer than most Queens neighborhoods because of the north-edge geography. Cross Island Parkway and Whitestone Bridge feeder traffic affects routing.`,
      landmarks: `Common Whitestone tire-change origins: Cross Island Parkway service road; Whitestone Bridge approach lanes; Whitestone core 1-family driveways; Beechhurst waterfront homes (salt-air dry-rot); 14th Avenue commercial. We do not service the Whitestone Bridge, Cross Island Parkway main lanes, or Throgs Neck Bridge approach.`,
    },
    whyHeavyDemand: `Whitestone tire-change demand has three drivers: (1) Cross Island Parkway service road takes commuter traffic producing pothole damage year-round; (2) Whitestone Bridge approach accumulates pothole damage from heavy commuter and commercial truck traffic; (3) Beechhurst waterfront salt-air accelerates tire dry-rot on older cars near the East River.`,
    scenarios: [
      ['Cross Island Parkway service road pothole', 'Hit a pothole at speed on the service road.'],
      ['Whitestone Bridge approach pothole', 'Got off the bridge approach, sidewall damage.'],
      ['Suburban driveway curb strike', 'Misjudged the curb on the driveway.'],
      ['Beechhurst salt-air dry-rot', 'Waterfront older car, sidewall split.'],
      ['Older multi-car household sedan dry-rot', 'Third or fourth car, aging tires.'],
      ['14th Avenue pothole', 'Pothole on 14th Avenue, sidewall damage.'],
    ],
    cellFaqs: [
      ['Why is Whitestone response so much longer than Astoria?', 'Whitestone sits at the north edge of Queens, far from our central staging zones (~32 min vs ~20 min for Astoria).'],
      ['Are Beechhurst waterfront tire-change calls common?', 'Yes. Salt-air-accelerated dry-rot is a real factor on older cars parked near the East River.'],
      ['Can you help on the Whitestone Bridge or Cross Island Parkway?', 'No. Whitestone Bridge, Cross Island Parkway main lanes, and Throgs Neck Bridge approach are NYPD-rotation only.'],
      ['Do you handle suburban driveway curb-strike calls?', 'Yes. Direct front-of-home access typical.'],
      ['What if my older car has a 5+ year-old spare?', 'Older spares can have dry-rot too. We inspect before mounting; if the spare is also dry-rotted, we tow to a tire shop.'],
    ],
  },

  'college-point': {
    heroSubline: `<strong>$125 flat per service</strong>. College Point tire-change calls cluster on College Point Boulevard big-box parking lot debris (nails and screws from construction shopping zones), BJs/IKEA parking lot pothole damage, Cross Island Parkway service road potholes, and suburban driveway curb damage.`,
    whatIs: {
      p1: `Roadside tire-change service in College Point has a big-box retail layer. College Point Boulevard between 14th Avenue and Whitestone Expressway is one of NYC's densest big-box retail corridors — BJs Wholesale, IKEA, Target, Best Buy. Construction debris in parking lots (nails, screws from periodic store renovations and inventory restocking) produces tread-puncture calls regularly. Pothole damage on the boulevard itself adds sidewall blowout calls.`,
      p2: `College Point's residential character is similar to Whitestone — 1-family detached and 1-2 family attached homes with driveways. Driveway curb-strike damage and cold-morning low-pressure calls are common. Powell Cove waterfront salt-air accelerates tire dry-rot on older cars parked near the water.`,
    },
    whenToCall: [
      ['BJs Wholesale parking lot — debris puncture', 'Picked up a nail in the BJs lot from construction debris.'],
      ['IKEA parking lot — pothole or debris', 'Pothole or nail in the IKEA lot, tread or sidewall damage.'],
      ['College Point Boulevard pothole — sidewall blowout', 'Hit a pothole on College Point Boulevard, sidewall blew.'],
      ['Cross Island Parkway service road — pothole damage', 'Pothole on the Cross Island service road.'],
      ['Suburban driveway curb strike', 'Misjudged the curb on the driveway.'],
      ['Powell Cove waterfront — salt-air dry-rot', 'Older car parked near Powell Cove, sidewall split from salt-air degradation.'],
    ],
    coverage: {
      intro: `Tire-change service across College Point covers the College Point core (between 14th Avenue and 28th Avenue, west of Cross Island Parkway), Whitestone-adjacent (eastern blocks), the Malba border, and the College Point Boulevard big-box retail corridor.`,
      why: `College Point response is ~32 minutes average. Big-box retail parking lots have direct service-vehicle access. Weekend peak shopping hours can add 5-8 minutes.`,
      landmarks: `Common College Point tire-change origins: BJs Wholesale parking lot; IKEA parking lot; Target parking lot; College Point Boulevard pothole zones; Cross Island Parkway service road; Powell Cove waterfront homes; College Point residential blocks. We do not service the Whitestone Bridge, Cross Island Parkway main lanes, or Throgs Neck Bridge approach.`,
    },
    whyHeavyDemand: `College Point tire-change demand has three drivers: (1) the College Point Boulevard big-box retail corridor produces a distinctive parking-lot debris-puncture call pattern at BJs, IKEA, and Target; (2) College Point Boulevard pothole damage from heavy retail-shopping traffic; (3) Powell Cove waterfront salt-air accelerates tire dry-rot on older cars.`,
    scenarios: [
      ['BJs Wholesale debris puncture', 'Nail in the BJs parking lot.'],
      ['IKEA pothole or debris', 'Tire damage in the IKEA lot.'],
      ['College Point Boulevard pothole', 'Hit a pothole on the boulevard.'],
      ['Cross Island Parkway service road pothole', 'Pothole damage on the service road.'],
      ['Suburban driveway curb strike', 'Curbed the wheel on the driveway.'],
      ['Powell Cove salt-air dry-rot', 'Older waterfront car, sidewall split.'],
    ],
    cellFaqs: [
      ['Do you respond to BJs, IKEA, and Target parking lot tire-change calls?', 'Yes — common College Point call type. Tell us which lot, your row, and the vehicle make/model.'],
      ['Why are big-box parking lot debris-puncture calls common?', 'Periodic store renovations and inventory restocking leave stray nails and screws on driving lanes.'],
      ['Are Powell Cove waterfront calls common?', 'Yes. Salt-air-accelerated dry-rot is a real factor on older cars parked near the East River and Powell Cove.'],
      ['Can you help on the Whitestone Bridge or Cross Island Parkway?', 'No. Whitestone Bridge, Cross Island Parkway main lanes, and Throgs Neck Bridge approach are NYPD-rotation only.'],
      ['How does College Point response compare to Whitestone?', 'About the same (~32 min) — both at the north edge of Queens.'],
    ],
  },

  'fresh-meadows': {
    heroSubline: `<strong>$125 flat per service</strong>. Fresh Meadows tire-change calls cluster on LIE service road potholes (very rough corridor), Grand Central Parkway service road potholes, Fresh Meadows Co-op parking lot tire damage, Union Turnpike pothole, and driveway curb damage. Bus-only transit means high household car ownership and aging tire fleet.`,
    whatIs: {
      p1: `Roadside tire-change service in Fresh Meadows is shaped by LIE and Grand Central Parkway adjacency. Both service roads handle heavy commuter and commercial-truck traffic and produce pothole damage year-round. The LIE service road through Fresh Meadows is one of Queens\' rougher pothole zones. Sidewall blowouts on both service roads are daily call types.`,
      p2: `Fresh Meadows Co-op — the large 1940s garden-apartment development — has thousands of units and shared parking lots. Lot debris (nails, screws from periodic maintenance work) produces tread punctures. Older long-time Co-op residents have older daily-driver sedans with aging tires (5+ years) prone to dry-rot. Limited subway access forces high household car ownership across Hillcrest, Utopia, and Cunningham Park areas.`,
    },
    whenToCall: [
      ['LIE service road — pothole sidewall blowout', 'Hit a pothole on the LIE service road through Fresh Meadows.'],
      ['Grand Central Parkway service road — pothole damage', 'Pothole on the GCP service road.'],
      ['Fresh Meadows Co-op parking lot — debris puncture', 'Picked up a nail in the Co-op parking lot from maintenance debris.'],
      ['Union Turnpike pothole — sidewall damage', 'Hit a pothole on Union Turnpike.'],
      ['Driveway curb strike — Hillcrest', 'Misjudged the curb pulling into the Hillcrest driveway.'],
      ['Older Co-op resident sedan — dry-rot sidewall', 'Older daily-driver sedan, 5+ year tires, dry-rot failure.'],
    ],
    coverage: {
      intro: `Tire-change service across Fresh Meadows covers the Fresh Meadows core (the Co-op apartment blocks between Union Turnpike and 73rd Avenue), Hillcrest, Utopia, and the Cunningham Park area.`,
      why: `Fresh Meadows response is ~32 minutes average. Distance from central-Queens staging zones is the main factor.`,
      landmarks: `Common Fresh Meadows tire-change origins: LIE service road; Grand Central Parkway service road; Fresh Meadows Co-op parking lots; Union Turnpike pothole zones; Cunningham Park edge residential. We do not service the Long Island Expressway main lanes, Grand Central Parkway main lanes, Clearview Expressway, or Cross Island Parkway.`,
    },
    whyHeavyDemand: `Fresh Meadows tire-change demand has three drivers: (1) LIE service road through Fresh Meadows is one of Queens\' rougher pothole zones, with heavy commuter and commercial-truck traffic accelerating damage; (2) Fresh Meadows Co-op parking lots have periodic maintenance debris producing tread punctures; (3) limited subway access forces high household car ownership with older daily-driver vehicles prone to dry-rot.`,
    scenarios: [
      ['LIE service road sidewall blowout', 'Hit a pothole at speed.'],
      ['GCP service road pothole', 'Pothole on the GCP service road.'],
      ['Co-op parking lot debris puncture', 'Nail in the Co-op lot from maintenance debris.'],
      ['Union Turnpike pothole', 'Pothole on Union Turnpike.'],
      ['Hillcrest driveway curb strike', 'Curbed the wheel on the driveway.'],
      ['Older Co-op sedan dry-rot', 'Older daily-driver, sidewall split.'],
    ],
    cellFaqs: [
      ['Do you service Fresh Meadows Co-op parking lots?', 'Yes. Many lots require resident-pass entry — coordinate with management.'],
      ['Why is the LIE service road so rough on tires?', 'Heavy commuter and commercial-truck traffic, plus the freeze-thaw cycle, accelerates pothole formation. Sidewall blowouts are a daily call type.'],
      ['Can you help on the LIE main lanes?', 'No. LIE main lanes, Grand Central Parkway, Clearview Expressway, and Cross Island Parkway are NYPD-rotation only.'],
      ['Is multi-language dispatch available?', 'Dispatch is English-primary but is familiar with Yiddish, Hebrew, Korean, and Spanish neighborhood references.'],
      ['How does Fresh Meadows response compare to Briarwood?', '~32 min Fresh Meadows vs ~28 min Briarwood — Fresh Meadows is further east.'],
    ],
  },
};
